#!/bin/csh -f

#set top = `(chdir .. ; pwd)`
set top = `pwd`

setenv CC 	"gcc"
setenv CXX 	"g++"

echo "Building database support libraries ...."
echo "  (Using toplevel directory '"$top"' ....)"

# Global options.
set	gopts = "--prefix=$top --exec-prefix=$top --disable-shared"

#echo "    Cleaning files ...."
#./mkclean

echo -n "    Building SQLITE libs ...."
set	opts = "$gopts"
  (chdir sqlite ;  \
    ./configure $opts  				 >& _spool ; \
    make clean 					>>& _spool ; \
    make 					>>& _spool ; \
    make install 				>>& _spool )
  echo "done"


/bin/rm -rf lib/*.la lib/*.so.* lib/*.so lib/pkgconfig share
