.TH "dtsClient" 3 "11 Apr 2014" "Version v1.0" "DTS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dtsClient \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dts.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBclientPort\fP"
.br
.ti -1c
.RI "char \fBclientUrl\fP [SZ_FNAME]"
.br
.ti -1c
.RI "char \fBclientHost\fP [SZ_FNAME]"
.br
.ti -1c
.RI "char \fBclientDir\fP [SZ_FNAME]"
.br
.ti -1c
.RI "char \fBclientCopy\fP [SZ_FNAME]"
.br
.ti -1c
.RI "char \fBclientIP\fP [SZ_FNAME]"
.br
.ti -1c
.RI "char \fBclientName\fP [SZ_FNAME]"
.br
.ti -1c
.RI "char \fBclientNet\fP [SZ_FNAME]"
.br
.ti -1c
.RI "int \fBclientLoPort\fP"
.br
.ti -1c
.RI "int \fBclientHiPort\fP"
.br
.ti -1c
.RI "int \fBclientContact\fP"
.br
.ti -1c
.RI "int \fBconn\fP"
.br
.ti -1c
.RI "int \fBactive\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDTS\fP client connection. 

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS from the source code.
