.TH "dtsClient.c" 3 "11 Apr 2014" "Version v1.0" "DTS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dtsClient.c \- \fBDTS\fP Client-side methods.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <ctype.h>\fP
.br
\fC#include <xmlrpc-c/base.h>\fP
.br
\fC#include <xmlrpc-c/client.h>\fP
.br
\fC#include <xmlrpc-c/server.h>\fP
.br
\fC#include <xmlrpc-c/server_abyss.h>\fP
.br
\fC#include 'dts.h'\fP
.br

.SH "Detailed Description"
.PP 
\fBDTS\fP Client-side methods. 

DTSCLIENT.C
.PP
Client-side methods.
.PP
\fBAuthor:\fP
.RS 4
Mike Fitzpatrick, NOAO 
.RE
.PP
\fBDate:\fP
.RS 4
6/10/09 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS from the source code.
