.TH "Param" 3 "11 Apr 2014" "Version v1.0" "DTS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Param \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dts.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [SZ_PATH]"
.br
.ti -1c
.RI "char \fBvalue\fP [SZ_PATH]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Arbitrary keyword/value parameter. 

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS from the source code.
