.TH "qStat" 3 "11 Apr 2014" "Version v1.0" "DTS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qStat \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dts.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [SZ_PATH]"
.br
.ti -1c
.RI "char \fBinfile\fP [SZ_PATH]"
.br
.ti -1c
.RI "char \fBoutfile\fP [SZ_PATH]"
.br
.ti -1c
.RI "char \fBstatus\fP [SZ_PATH]"
.br
.ti -1c
.RI "char \fBtype\fP [SZ_PATH]"
.br
.ti -1c
.RI "char \fBsrc\fP [SZ_PATH]"
.br
.ti -1c
.RI "int \fBcurrent\fP"
.br
.ti -1c
.RI "int \fBpending\fP"
.br
.ti -1c
.RI "int \fBqcount\fP"
.br
.ti -1c
.RI "float \fBrate\fP"
.br
.ti -1c
.RI "float \fBtime\fP"
.br
.ti -1c
.RI "float \fBsize\fP"
.br
.ti -1c
.RI "float \fBtotal\fP"
.br
.ti -1c
.RI "int \fBnxfer\fP"
.br
.ti -1c
.RI "float \fBMbs\fP"
.br
.ti -1c
.RI "int \fBcanceledxfers\fP"
.br
.ti -1c
.RI "int \fBnumflushes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structs for status information. 

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS from the source code.
