.TH "xferStat" 3 "11 Apr 2014" "Version v1.0" "DTS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xferStat \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dts.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBfsize\fP"
.br
.ti -1c
.RI "float \fBtput_mb\fP"
.br
.ti -1c
.RI "float \fBtput_MB\fP"
.br
.ti -1c
.RI "float \fBtime\fP"
.br
.ti -1c
.RI "int \fBsec\fP"
.br
.ti -1c
.RI "int \fBusec\fP"
.br
.ti -1c
.RI "int \fBstat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Transfer stats 

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS from the source code.
