dts.c File Reference
DTS interface procedures,.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <ctype.h>
#include <pthread.h>
#include <netdb.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <signal.h>
#include <fcntl.h>
#include `dts.h`
#include `dtsdb.h`
Defines
#define _DTS_SRC_ 1
Functions
DTS * dtsInit (char *config, int port, char *host, char *sroot, int initialize)
Initialize the DTS daemon structure.
void dts_initCopyMode (DTS *dts, char *host, int port)
void dts_initServerRoot (DTS *dts)
void dtsFree (DTS *dts)
Free the DTS daemon structure.
void dts_connectToMonitor (DTS *dts)
Connoct to the logging monitor and/open log file.
void dtsErrorExit (char *msg)
Connect to the logging monitor and/open log file.
void dtsErrorWarn (char *msg)
Connect to the logging monitor and/open log file.
Variables
int queue_delay = 0
int first_write = 1
Detailed Description
DTS interface procedures,.
DTS.C -- DTS interface procedures,
Author: Mike Fitzpatrick, NOAO
Date: 6/15/09
Function Documentation
void dts_connectToMonitor (DTS * dts)
Connoct to the logging monitor and/open log file.
DTS_CONNECTTOMONITOR -- Connect to the logging monitor and/open log file.
Parameters:
dts DTS struct pointer
Returns: nothing
Referenced by dtsDaemonize().
void dts_initCopyMode (DTS * dts, char * host, int port)
DTS_INITCOPYMODR -- Initialize the server for copy mode.
References dts_getLocalIP(), and dts_localCwd().
Referenced by dtsInit().
void dts_initServerRoot (DTS * dts)
DTS_INITSERVERROOT -- Initialize the server root directory.
References dts_queueSetCurrent().
Referenced by dts_SetRoot().
void dtsErrorExit (char * msg)
Connect to the logging monitor and/open log file.
DTSERROREXIT -- Print an error message and exit.
Parameters:
msg Error message
Returns: nothing
References dtsLog().
void dtsErrorWarn (char * msg)
Connect to the logging monitor and/open log file.
DTSERRORWARN -- Print a warning message.
Parameters:
msg Warning message
Returns: nothing
References dtsLog().
void dtsFree (DTS * dts)
Free the DTS daemon structure.
DTSFREE -- Free the DTS daemon structure.
Parameters:
dts DTS struct pointer
Returns: nothing
DTS * dtsInit (char * config, int port, char * host, char * root, int initialize)
Initialize the DTS daemon structure.
DTSINIT -- Initialize the DTS daemon structure.
Parameters:
config DTS config file
port DTS server port number
host DTS server host name
root DTS root directory
initialize initialize root directory?
Returns: pointer to DTS structure
References dts_cfgPath(), dts_initCopyMode(), dts_isDir(), dts_loadConfigDir(), and dts_loadConfigFile().