dtsASync.c File Reference
DTS asynchronous command methods.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include `dts.h`
Functions
int dts_nullResponse (void *data)
Asyncronous null handler.
Detailed Description
DTS asynchronous command methods.
DTSASYNC.C
Methods used in Asynchronous commands.
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
int dts_nullResponse (void * data)
Asyncronous null handler.
DTS_NULLRESPONSE -- Asyncronous null handler.
Parameters:
data xml caller data
Returns: status code
Referenced by dtsLog(), dtsLogMsg(), and dtsLogStat().