dtsCommands.c File Reference
Client-callable DTS commands.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <fcntl.h>
#include `dts.h`
#include `dtsPSock.h`
Defines
#define DEBUG CMD_DEBUG
#define MAX_TRIES 5
#define MAX_TRIES 5
Functions
void dts_cmdInit ()
int dts_getClient (char *host)
int dts_hostAccess (char *host, char *path, int mode)
Check file access on a host DTS machine.
char * dts_hostCat (char *host, char *fname)
Cat a file.
int dts_hostChecksum (char *host, char *fname, unsigned int *sum32, unsigned int *crc, char **md5)
int dts_hostCopy (char *host, char *old, char *new)
Copy a file on a host DTS machine.
char * dts_hostCfg (char *host, int quiet)
int dts_hostChmod (char *host, char *path, mode_t mode)
Change the mode of a file on a remote DTS.
char * dts_hostCwd (char *host)
Get the cwd of the DTS host.
int dts_hostDel (char *host, char *path, char *passwd, int recursive)
Delete a file on a DTS host.
char * dts_hostDir (char *host, char *path, int lsLong)
Get a directory listing from a DTS host.
char * dts_hostDestDir (char *host, char *qname)
Get a listing for a queue's delivery directory.
int dts_hostIsDir (char *host, char *path)
Test whether the given path is a directory.
int dts_hostDiskFree (char *host, char *path)
Get the space available on the give containing a specified path.
int dts_hostDiskUsed (char *host, char *path)
Get the space available on the give containing a specified path.
char * dts_hostEcho (char *host, char *str)
Have a host DTS machine echo a string.
long dts_hostFSize (char *host, char *path)
Get a file size on a remote DTS host.
long dts_hostFMode (char *host, char *path)
Get a file mode on a remote DTS host.
int dts_hostFTime (char *host, char *path, char *mode)
Get a file time on a remote DTS host.
int dts_hostFGet (char *host, char *fname, char *local, int blk)
Get a remote file to a local file.
int dts_hostMkdir (char *host, char *path)
Make a directory on a host DTS machine.
int dts_hostPoke (char *host)
Poke a host DTS machine, i.e. ping w/out a restart.
int dts_hostPing (char *host)
Ping a host DTS machine.
int dts_hostPingSleep (char *host, int time)
Ping a host DTS machine.
int dts_hostSvrPing (char *host, int time)
char * dts_hostPingStr (char *host)
Ping a host DTS machine.
int dts_hostPingArray (char *host)
Ping a host DTS machine.
int dts_hostRemotePing (char *local, char *remote)
Tell one machine to ping another.
int dts_hostPrealloc (char *host, char *path, long size)
Prealloc space on a host DTS machine.
int dts_hostRename (char *host, char *old, char *new)
Rename a file on a host DTS machine.
int dts_hostStat (char *host, char *path, struct stat *st)
Update access time on a host DTS machine.
int dts_hostSetRoot (char *host, char *path)
Set the root directory of a DTS.
int dts_hostSetDbg (char *host, char *flag)
Set a debug flag on a DTS node.
int dts_hostUnsetDbg (char *host, char *flag)
Unset a debug flag on the DTS node.
int dts_hostTouch (char *host, char *path)
Update access time on a host DTS machine.
unsigned char * dts_hostRead (char *host, char *fname, int offset, int sz, int *retnb)
Read a chunk from a file.
char * dts_hostSrc (char *host, char *qname)
Get the source of the named queue.
char * dts_hostDest (char *host, char *qname)
Get the destination of the named queue.
int dts_hostStartQueue (char *host, char *qname)
Start the named queue.
int dts_hostShutdownQueue (char *host, char *qname)
Shutdown the named queue.
char * dts_hostPrintQueueCfg (char *host, char *qname)
Print the configuration of the named queue.
int dts_hostGetQueueStat (char *host, char *qname)
Get the status flag on the named queue.
int dts_hostSetQueueStat (char *host, char *qname, int val)
Set the status flag on the named queue.
char * dts_hostGetQueueDir (char *host, char *qname)
Get the queue deliverDirectory.
int dts_hostSetQueueDir (char *host, char *qname, char *dir)
Set the queue deliveryDir.
char * dts_hostGetQueueCmd (char *host, char *qname)
Get the queue deliverCmd.
int dts_hostSetQueueCmd (char *host, char *qname, char *cmd)
Set the queue deliveryCmd.
char * dts_hostGetCopyDir (char *host)
Get the DTS copy directory.
int dts_hostExecCmd (char *host, char *ewd, char *cmd)
Execute the given command.
int dts_hostStopQueue (char *host, char *qname)
Stop the named queue.
int dts_hostFlushQueue (char *host, char *qname)
Stop the named queue.
int dts_hostPokeQueue (char *host, char *qname)
Poke the named queue.
int dts_hostPauseQueue (char *host, char *qname)
Pause the named queue.
char * dts_hostListQueue (char *host, char *qname)
List the named queue.
int dts_hostSetQueueCount (char *host, char *qname, int count)
Set the pending count for the named queue.
int dts_hostGetQueueCount (char *host, char *qname)
Get the pending count for the named queue.
int dts_hostAbort (char *host, char *passwd)
Just freakin' die.
int dts_hostContact (char *host)
Attempt to contact/start the remote DTS.
int dts_hostShutdown (char *host, char *passwd)
Just freakin' die.
int dts_hostSet (char *host, char *class, char *key, char *val)
Set a value on the remote host.
char * dts_hostGet (char *host, char *class, char *key)
Get a value from the remote host.
int dts_hostUpStats (char *host, char *qname, xferStat *xfs)
Update the transfer statistics.
int dts_hostNodeStat (char *host, char *qname, int errs, nodeStat *ns)
int dts_isLocal (char *host)
Is the given host the local machine?
int dts_closeClient (int client)
Variables
DTS * dts
int dts_monitor
Detailed Description
Client-callable DTS commands.
DTSCOMMANDS.C -- Client-callable DTS commands.
Author: Mike Fitzpatrick, NOAO
Date: 6/15/09
Function Documentation
int dts_closeClient (int client)
DTS_CLOSECLIENT - Close a client handle for the given host.
Referenced by dts_hostAbort(), dts_hostAccess(), dts_hostCat(), dts_hostChmod(), dts_hostCopy(), dts_hostCwd(), dts_hostDel(), dts_hostDest(), dts_hostDestDir(), dts_hostDir(), dts_hostDiskFree(), dts_hostDiskUsed(), dts_hostEcho(), dts_hostEndTransfer(), dts_hostExecCmd(), dts_hostFGet(), dts_hostFlushQueue(), dts_hostFMode(), dts_hostFSize(), dts_hostFTime(), dts_hostGet(), dts_hostGetCopyDir(), dts_hostGetQueueCmd(), dts_hostGetQueueCount(), dts_hostGetQueueDir(), dts_hostGetQueueStat(), dts_hostInitTransfer(), dts_hostIsDir(), dts_hostListQueue(), dts_hostMkdir(), dts_hostPauseQueue(), dts_hostPing(), dts_hostPingArray(), dts_hostPingSleep(), dts_hostPingStr(), dts_hostPoke(), dts_hostPokeQueue(), dts_hostPrealloc(), dts_hostPrintQueueCfg(), dts_hostQueueAccept(), dts_hostQueueComplete(), dts_hostQueueRelease(), dts_hostQueueValid(), dts_hostRead(), dts_hostRemotePing(), dts_hostRename(), dts_hostSet(), dts_hostSetDbg(), dts_hostSetQueueCmd(), dts_hostSetQueueControl(), dts_hostSetQueueCount(), dts_hostSetQueueDir(), dts_hostSetQueueStat(), dts_hostSetRoot(), dts_hostShutdown(), dts_hostShutdownQueue(), dts_hostSrc(), dts_hostStartQueue(), dts_hostStat(), dts_hostStopQueue(), dts_hostTouch(), dts_hostUnsetDbg(), dts_hostUpStats(), dts_PingSleep(), dts_xferFile(), dtsLog(), dtsLogMsg(), and dtsLogStat().
void dts_cmdInit ()
DTS_CMDINIT - Initialize the command interface.
Referenced by dts_hostAbort(), dts_hostAccess(), dts_hostCat(), dts_hostChmod(), dts_hostCopy(), dts_hostCwd(), dts_hostDel(), dts_hostDest(), dts_hostDestDir(), dts_hostDir(), dts_hostDiskFree(), dts_hostDiskUsed(), dts_hostEcho(), dts_hostEndTransfer(), dts_hostExecCmd(), dts_hostFGet(), dts_hostFlushQueue(), dts_hostFMode(), dts_hostFrom(), dts_hostFSize(), dts_hostFTime(), dts_hostGet(), dts_hostGetCopyDir(), dts_hostGetQueueCmd(), dts_hostGetQueueCount(), dts_hostGetQueueDir(), dts_hostGetQueueStat(), dts_hostInitTransfer(), dts_hostIsDir(), dts_hostListQueue(), dts_hostMkdir(), dts_hostPauseQueue(), dts_hostPing(), dts_hostPingArray(), dts_hostPingSleep(), dts_hostPingStr(), dts_hostPoke(), dts_hostPokeQueue(), dts_hostPrealloc(), dts_hostPrintQueueCfg(), dts_hostQueueAccept(), dts_hostQueueComplete(), dts_hostQueueRelease(), dts_hostQueueValid(), dts_hostRead(), dts_hostRemotePing(), dts_hostRename(), dts_hostSet(), dts_hostSetDbg(), dts_hostSetQueueCmd(), dts_hostSetQueueControl(), dts_hostSetQueueCount(), dts_hostSetQueueDir(), dts_hostSetQueueStat(), dts_hostSetRoot(), dts_hostShutdown(), dts_hostShutdownQueue(), dts_hostSrc(), dts_hostStartQueue(), dts_hostStat(), dts_hostStopQueue(), dts_hostTo(), dts_hostTouch(), dts_hostUnsetDbg(), and dts_hostUpStats().
int dts_getClient (char * host)
DTS_GETCLIENT - Get a client handle for the given host.
Referenced by dts_hostAbort(), dts_hostAccess(), dts_hostCat(), dts_hostChmod(), dts_hostCopy(), dts_hostCwd(), dts_hostDel(), dts_hostDest(), dts_hostDestDir(), dts_hostDir(), dts_hostDiskFree(), dts_hostDiskUsed(), dts_hostEcho(), dts_hostEndTransfer(), dts_hostExecCmd(), dts_hostFGet(), dts_hostFlushQueue(), dts_hostFMode(), dts_hostFSize(), dts_hostFTime(), dts_hostGet(), dts_hostGetCopyDir(), dts_hostGetQueueCmd(), dts_hostGetQueueCount(), dts_hostGetQueueDir(), dts_hostGetQueueStat(), dts_hostInitTransfer(), dts_hostIsDir(), dts_hostListQueue(), dts_hostMkdir(), dts_hostPauseQueue(), dts_hostPing(), dts_hostPingArray(), dts_hostPingSleep(), dts_hostPingStr(), dts_hostPoke(), dts_hostPokeQueue(), dts_hostPrealloc(), dts_hostPrintQueueCfg(), dts_hostQueueAccept(), dts_hostQueueComplete(), dts_hostQueueRelease(), dts_hostQueueValid(), dts_hostRead(), dts_hostRemotePing(), dts_hostRename(), dts_hostSet(), dts_hostSetDbg(), dts_hostSetQueueCmd(), dts_hostSetQueueControl(), dts_hostSetQueueCount(), dts_hostSetQueueDir(), dts_hostSetQueueStat(), dts_hostSetRoot(), dts_hostShutdown(), dts_hostShutdownQueue(), dts_hostSrc(), dts_hostStartQueue(), dts_hostStat(), dts_hostStopQueue(), dts_hostTouch(), dts_hostUnsetDbg(), dts_hostUpStats(), dts_PingSleep(), dts_xferFile(), dtsLog(), dtsLogMsg(), and dtsLogStat().
int dts_hostAbort (char * host, char * passwd)
Just freakin' die.
DTS_HOSTABORT -- Exit the DTS without prejudice.
Parameters:
host host machine name (or IP string)
passwd DTS host passwd
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostAccess (char * host, char * path, int mode)
Check file access on a host DTS machine.
DTS_HOSTACCESS -- Check file access on a host DTS machine.
Parameters:
host host machine name (or IP string)
path path name to be checked
mode access mode (R_OK|W_OK|X_OK, default F_OK)
Returns: 1 (one) if access allowed/file exists
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
Referenced by dts_hostFrom().
char* dts_hostCat (char * host, char * fname)
Cat a file.
DTS_HOSTCAT -- Cat a file.
Parameters:
host host machine name (or IP string)
fname file name to be read
Returns: Current working dir of DTS host
References base64_decode(), dts_closeClient(), dts_cmdInit(), dts_getClient(), and dts_hostFSize().
int dts_hostChmod (char * host, char * path, mode_t mode)
Change the mode of a file on a remote DTS.
DTS_HOSTCHMOD -- Change the mode of a file on a remote DTS.
Parameters:
host host machine name (or IP string)
path path to file
mode file access mode
Returns: status (OK or ERR)
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
Referenced by dts_xferDirTo(), and dts_xferFile().
int dts_hostContact (char * host)
Attempt to contact/start the remote DTS.
DTS_HOSTCONTACT -- Attempt to contact/start the remote DTS.
Parameters:
host host machine name (or IP string)
Returns: 1 (one) if DTS responds.
References dts_openClientSocket().
Referenced by dts_hostPing(), and dts_verifyDTS().
int dts_hostCopy (char * host, char * old, char * new)
Copy a file on a host DTS machine.
DTS_HOSTCOPY -- Copy a file on a host DTS machine.
Parameters:
host host machine name (or IP string)
old old path
new new path
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
char* dts_hostCwd (char * host)
Get the cwd of the DTS host.
DTS_HOSTCWD -- Get the cwd of the DTS host.
Parameters:
host host machine name (or IP string)
Returns: Current working dir of DTS host
References dts_closeClient(), dts_cmdInit(), dts_getClient(), and dts_resolveHost().
int dts_hostDel (char * host, char * path, char * passwd, int recursive)
Delete a file on a DTS host.
DTS_HOSTDEL -- Delete a file on a DTS host.
Parameters:
host host machine name (or IP string)
path path to file to be deleted
passwd DTS host passwd
recursive recursive delete?
Returns: success code
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
char* dts_hostDest (char * host, char * qname)
Get the destination of the named queue.
DTS_HOSTDEST -- Get the destination of the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: Current working dir of DTS host
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
char* dts_hostDestDir (char * host, char * qname)
Get a listing for a queue's delivery directory.
DTS_HOSTDESTDIR -- Get a listing for a queue's delivery directory
Parameters:
host host machine name (or IP string)
path queue name to list
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
char* dts_hostDir (char * host, char * path, int lsLong)
Get a directory listing from a DTS host.
DTS_HOSTDIR -- Get a directory listing from a DTS host.
Parameters:
host host machine name (or IP string)
path path on disk partition to be listed.
lsLong long listing?
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
Referenced by dts_xferDirFrom().
int dts_hostDiskFree (char * host, char * path)
Get the space available on the give containing a specified path.
DTS_HOSTDISKFREE -- Get the space available on the DTS host containing a specified path.
Parameters:
host host machine name (or IP string)
path path on disk partition to be checked.
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostDiskUsed (char * host, char * path)
Get the space available on the give containing a specified path.
DTS_HOSTDISKUSED -- Get the space used on the DTS host containing a specified path.
Parameters:
host host machine name (or IP string)
path path on disk partition to be checked.
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
char* dts_hostEcho (char * host, char * str)
Have a host DTS machine echo a string.
DTS_HOSTECHO -- Have a host DTS machine echo a string.
Parameters:
host host machine name (or IP string)
str string to echo
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostExecCmd (char * host, char * ewd, char * cmd)
Execute the given command.
DTS_HOSTEXECCMD -- Execute the given command.
Parameters:
host host machine name (or IP string)
ewd effective working dir
cmd queue delivery command
Returns: status flag
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostFGet (char * host, char * fname, char * local, int blk)
Get a remote file to a local file.
DTS_HOSTFGET -- Get a remote file to a local file.
Parameters:
host host machine name (or IP string)
fname remote file name to be read
local local file name to write
blk i/o block size
Returns: status of transfer
References base64_decode(), dts_closeClient(), dts_cmdInit(), dts_fileWrite(), dts_getClient(), dts_hostFSize(), and transferMB().
int dts_hostFlushQueue (char * host, char * qname)
Stop the named queue.
DTS_HOSTFLUSHQUEUE -- Stop the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: status
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
long dts_hostFMode (char * host, char * path)
Get a file mode on a remote DTS host.
DTS_HOSTFMODE -- Get a file mode on a remote DTS host.
Parameters:
host host machine name (or IP string)
path pathname to be checked
Returns: size (bytes) of file
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
Referenced by dts_hostFrom(), and dts_xferDirFrom().
long dts_hostFSize (char * host, char * path)
Get a file size on a remote DTS host.
DTS_HOSTFSIZE -- Get a file size on a remote DTS host.
Parameters:
host host machine name (or IP string)
path pathname to be checked
Returns: size (bytes) of file
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
Referenced by dts_hostCat(), dts_hostFGet(), dts_hostFrom(), dts_hostRead(), and dts_xferDirFrom().
int dts_hostFTime (char * host, char * path, char * mode)
Get a file time on a remote DTS host.
DTS_HOSTFTIME -- Get a file time on a remote DTS host.
Parameters:
host host machine name (or IP string)
path pathname to be checked
mode mode to check ('c'reate, 'm'odified, 'a'ccess)
Returns: time (seconds)
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
char* dts_hostGet (char * host, char * class, char * key)
Get a value from the remote host.
DTS_HOSTGET -- Get a value from the remote host.
Parameters:
host host machine name (or IP string)
class class
key keyword
Returns: value from remote DTS system
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
char* dts_hostGetCopyDir (char * host)
Get the DTS copy directory.
DTS_HOSTGETCOPYDIR -- Get the DTS copy directory
Parameters:
host host machine name (or IP string)
Returns: delivery directory for queue
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
char* dts_hostGetQueueCmd (char * host, char * qname)
Get the queue deliverCmd.
DTS_HOSTGETQUEUECMD -- Get the queue deliverCmd.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: delivery directory for queue
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostGetQueueCount (char * host, char * qname)
Get the pending count for the named queue.
DTS_HOSTGETQUEUECOUNT -- Get the pending count for the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: status
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
char* dts_hostGetQueueDir (char * host, char * qname)
Get the queue deliverDirectory.
DTS_HOSTGETQUEUEDIR -- Get the queue deliverDirectory.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: delivery directory for queue
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostGetQueueStat (char * host, char * qname)
Get the status flag on the named queue.
DTS_HOSTGETQUEUESTAT -- Get the status flag on the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: status flag
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostIsDir (char * host, char * path)
Test whether the given path is a directory.
DTS_HOSTISDIR -- Test whether the given path is a directory.
Parameters:
host host machine name (or IP string)
path path to be tested.
Returns: 1 (one) if path is a directory, zero otherwise
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
Referenced by dts_hostFrom(), and dts_xferFile().
char* dts_hostListQueue (char * host, char * qname)
List the named queue.
DTS_HOSTLISTQUEUE -- List the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: status
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostMkdir (char * host, char * path)
Make a directory on a host DTS machine.
DTS_HOSTMKDIR -- Make a directory on a host DTS machine.
Parameters:
host host machine name (or IP string)
path directory to create
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
Referenced by dts_hostFrom(), dts_hostTo(), dts_xferDirTo(), and dts_xferFile().
int dts_hostPauseQueue (char * host, char * qname)
Pause the named queue.
DTS_HOSTPAUSEQUEUE -- Pause the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: status
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostPing (char * host)
Ping a host DTS machine.
DTS_HOSTPING -- Ping a host DTS machine.
Parameters:
host host machine name (or IP string)
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), dts_getClient(), and dts_hostContact().
Referenced by dts_remotePing(), and dts_verifyDTS().
int dts_hostPingArray (char * host)
Ping a host DTS machine.
DTS_HOSTPINGARRAY -- Ping a host DTS machine, array return.
Parameters:
host host machine name (or IP string)
Returns: sum of array values if DTS responds, -1 on error.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostPingSleep (char * host, int time)
Ping a host DTS machine.
DTS_HOSTPINGSLEEP -- Ping a host DTS machine.
Parameters:
host host machine name (or IP string)
Returns: 1 (one) if DTS responds.
NOTE: This is implemented as an ASYNC call.
References dts_closeClient(), dts_cmdInit(), dts_getClient(), and dts_getLocalHost().
char* dts_hostPingStr (char * host)
Ping a host DTS machine.
DTS_HOSTPINGSTR -- Ping a host DTS machine, string return.
Parameters:
host host machine name (or IP string)
Returns: string response
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostPoke (char * host)
Poke a host DTS machine, i.e. ping w/out a restart.
DTS_HOSTPOKE -- Poke a host DTS machine, i.e. ping w/out a restart.
Parameters:
host host machine name (or IP string)
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostPokeQueue (char * host, char * qname)
Poke the named queue.
DTS_HOSTPOKEQUEUE -- Poke the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: status
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostPrealloc (char * host, char * path, long size)
Prealloc space on a host DTS machine.
DTS_HOSTPREALLOC -- Prealloc space on a host DTS machine.
Parameters:
host host machine name (or IP string)
path path to file to prealloc
size size of allocation
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
char* dts_hostPrintQueueCfg (char * host, char * qname)
Print the configuration of the named queue.
DTS_HOSTPRINTQUEUECFG -- Print the configuration of the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: status flag
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
unsigned char* dts_hostRead (char * host, char * fname, int offset, int sz, int * retnb)
Read a chunk from a file.
DTS_HOSTREAD -- Read a chunk from a file.
Parameters:
host host machine name (or IP string)
fname file name to be read
offset file offset
sz size of chunk to read
retnb number of bytes read
Returns: Current working dir of DTS host
References base64_decode(), dts_closeClient(), dts_cmdInit(), dts_getClient(), and dts_hostFSize().
int dts_hostRemotePing (char * local, char * remote)
Tell one machine to ping another.
DTS_HOSTREMOTEPING -- Tell one machine to ping another.
Parameters:
local local host machine name (or IP string)
remote remote machine name (or IP string)
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostRename (char * host, char * old, char * new)
Rename a file on a host DTS machine.
DTS_HOSTRENAME -- Rename a file on a host DTS machine.
Parameters:
host host machine name (or IP string)
old old path
new new path
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostSet (char * host, char * class, char * key, char * val)
Set a value on the remote host.
DTS_HOSTSET -- Set a value on the remote host.
Parameters:
host host machine name (or IP string)
class command class
key keyword
val value
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostSetDbg (char * host, char * flag)
Set a debug flag on a DTS node.
DTS_HOSTSETDBG -- Set a debug flag on a DTS node.
Parameters:
host host machine name (or IP string)
flag flag to set
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostSetQueueCmd (char * host, char * qname, char * cmd)
Set the queue deliveryCmd.
DTS_HOSTSETQUEUECMD -- Set the queue deliveryCmd.
Parameters:
host host machine name (or IP string)
qname queue name
cmd queue delivery command
Returns: status flag
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostSetQueueCount (char * host, char * qname, int count)
Set the pending count for the named queue.
DTS_HOSTSETQUEUECOUNT -- Set the pending count for the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
count queue count
Returns: status
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostSetQueueDir (char * host, char * qname, char * dir)
Set the queue deliveryDir.
DTS_HOSTSETQUEUEDIR -- Set the queue deliveryDir.
Parameters:
host host machine name (or IP string)
qname queue name
dir queue delivery directory
Returns: status flag
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostSetQueueStat (char * host, char * qname, int val)
Set the status flag on the named queue.
DTS_HOSTSETQUEUESTAT -- Set the status flag on the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
val queue status value
Returns: status flag
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostSetRoot (char * host, char * path)
Set the root directory of a DTS.
DTS_HOSTSETROOT -- Set the root directory of a DTS.
Parameters:
host host machine name (or IP string)
path path to touch
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostShutdown (char * host, char * passwd)
Just freakin' die.
DTS_HOSTSHUTDOWN -- Shutdown the DTS cleanly.
Parameters:
host host machine name (or IP string)
passwd DTS host passwd
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostShutdownQueue (char * host, char * qname)
Shutdown the named queue.
DTS_HOSTSHUTDOWNQUEUE -- Shutdown the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: status
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
char* dts_hostSrc (char * host, char * qname)
Get the source of the named queue.
DTS_HOSTSRC -- Get the source of the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: Current working dir of DTS host
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostStartQueue (char * host, char * qname)
Start the named queue.
DTS_HOSTSTARTQUEUE -- Start the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: status
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostStat (char * host, char * path, struct stat * st)
Update access time on a host DTS machine.
DTS_HOSTSTAT -- Get the file stat() information
Parameters:
host host machine name (or IP string)
path path to touch
st stat struct
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
cwd dts_hostStopQueue (char * host, char * qname)
Stop the named queue.
DTS_HOSTSTOPQUEUE -- Stop the named queue.
Parameters:
host host machine name (or IP string)
qname queue name
Returns: status
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostTouch (char * host, char * path)
Update access time on a host DTS machine.
DTS_HOSTTOUCH -- Update access time on a host DTS machine.
Parameters:
host host machine name (or IP string)
path path to touch
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
Referenced by dts_xferFile().
stat dts_hostUnsetDbg (char * host, char * flag)
Unset a debug flag on the DTS node.
DTS_HOSTUNSETDBG -- Unset a debug flag on the DTS node.
Parameters:
host host machine name (or IP string)
flag flag to set
Returns: 1 (one) if DTS responds.
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostUpStats (char * host, char * qname, xferStat * xfs)
Update the transfer statistics.
DTS_HOSTUPSTATS -- Update the transfer statistics.
Parameters:
host host machine name (or IP string)
qname queue name
xfs transfer stats
Returns: status
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
Referenced by dts_queueProcess().
int dts_isLocal (char * host)
Is the given host the local machine?
********************************************************************* Private Utility Procedures DTS_ISLOCAL -- Is the given host the local machine?
Parameters:
host host machine name (or IP string)
Returns: 1 (one) if DTS responds.
References dts_getLocalIP().