dtsConsole.c File Reference
DTS Console Interface.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
#include `dts.h`
Functions
int dts_monAttach (void *data)
int dts_monDetach (void *data)
int dts_monConsole (void *data)
Variables
DTS * dts
int dts_monitor
Detailed Description
DTS Console Interface.
DTSCONSOLE.C
DTS Console Interface - These are the methods implemented for he XML-RPC interace. These command are used from a variety of locations during the operation of the DTS (i.e. the queueing, logging or interactive environments.
monAttach - attach logging to the specified dtsmonitor
Author: Mike Fitzpatrick, NOAO
Date: 6/15/09
Function Documentation
int dts_monAttach (void * data)
DTS_MONATTACH -- Attach the DTS logging output to the dtsmon at the specified host.
Parameters:
data calling parameter data #
Returns: status (OK|ERR)
References dtsLog().
int dts_monConsole (void * data)
DTS_MONCONSOLE -- Request connection as a controlling console. We provide a (minimal security) password that must be supplied to grant access.
Parameters:
data calling parameter data #
Returns: status (OK|ERR)
References dtsLog().
int dts_monDetach (void * data)
DTS_MODETACH -- Detach the DTS logging output to the current dtsmon.
Parameters:
data calling parameter data #
Returns: status (OK|ERR)
References dtsLog().