dtsConfig.c File Reference
DTS Config File Interface.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <pthread.h>
#include <time.h>
#include <math.h>
#include <dirent.h>
#include <ctype.h>
#include `dtsPSock.h`
#include `dts.h`
Defines
#define CFG_DEBUG (getenv(`CFG_DBG`)!=NULL||access(`/tmp/CFG_DBG`,F_OK)==0)
#define DEBUG CFG_DEBUG
#define CON_GLOBAL 0
#define CON_DTS 1
#define CON_QUEUE 2
#define CON_XFER 3
#define CFG_NREQUIRED 9
Functions
char * dtsGets (char *s, int len, FILE *fd)
void dts_loadConfigDir (DTS *dts, char *cfg, char *dhost, int dport, char *droot, int initialize)
Load the DTS configuration file.
void dts_loadConfigFile (DTS *dts, char *cfg, char *dhost, int dport, char *droot, int initialize)
Load the DTS configuration file.
int dts_loadDefaultConfig (DTS *dts, char *host, int port)
dtsQueue * dts_newQueue (DTS *dts)
int dts_validateQueue (DTS *dts, dtsQueue *dtsq)
int dts_getQPort (DTS *dts, char *qname, int tport)
void dts_printQPorts (DTS *dts)
int dts_validPasswd (DTS *dts, char *passwd)
Validate a passwd against the host.
char * dts_nameToHost (DTS *dts, char *name)
Convert a DTS name to the host.
char * dts_nameToIP (DTS *dts, char *name)
Convert a DTS name to the host IP.
char * dts_cfgNameToHost (DTS *dts, char *name)
Convert a DTS name to the host name (2nd method).
char * dts_cfgNameToIP (DTS *dts, char *name)
Convert a DTS name to the host IP (2nd method).
char * dts_getLocalRoot ()
int dts_cfgQType (char *s)
Get the type of queue.
int dts_cfgQNode (char *s)
Get the node type of queue.
int dts_cfgQMethod (char *s)
Get the queue transfer method.
int dts_cfgQMode (char *s)
Get the trander mode (push or pull).
char * dts_cfgQTypeStr (int type)
Convert mode to string name.
char * dts_cfgQNodeStr (int node)
Convert dode to type string name.
char * dts_cfgQMethodStr (int method)
Convert method type to string name.
char * dts_cfgQModeStr (int mode)
Convert mode type to string name.
time_t dts_cfgInterval (char *intstr)
Get a timing interval (in sec) from the config value.
time_t dts_cfgStartTime (char *tstr)
Get a timing interval (in sec) from the config value.
char * dts_cfgPath ()
void dts_printConfig (DTS *dts)
char * dts_fmtConfig (DTS *dts)
Variables
int dts_monitor
int context = CON_GLOBAL
Detailed Description
DTS Config File Interface.
DTSCONFIG.C -- DTS Config File Interface
Author: Mike Fitzpatrick, NOAO
Date: 6/15/09
Function Documentation
time_t dts_cfgInterval (char * intstr)
Get a timing interval (in sec) from the config value.
DTS_CFGINTERVAL -- Get a timing interval (in sec) from the config value. Default unit is minutes, intervals may be specified in the form
<N>[h|m|s] run every <N> (h)ours, (m)in, or (s)ec
Parameters:
intstr interval value (string type)
Returns: interval in seconds
Referenced by dts_loadConfigFile().
char* dts_cfgNameToHost (DTS * dts, char * name)
Convert a DTS name to the host name (2nd method).
DTS_CFGNAMETOHOST -- Convert a DTS name to the host name (2nd method).
Parameters:
dts DTS struct
name DTS name string
Returns: host name
char* dts_cfgNameToIP (DTS * dts, char * name)
Convert a DTS name to the host IP (2nd method).
DTS_CFGNAMETOIP -- Convert a DTS name to the host IP (2nd method).
Parameters:
dts DTS struct
name DTS name string
Returns: IP name
Referenced by dts_resolveHost().
char* dts_cfgPath (void)
DTS_CFGPATH -- Construct a path to a user's `.dts_config` file.
Referenced by dtsInit().
int dts_cfgQMethod (char * s)
Get the queue transfer method.
DTS_CFGQMETHOD -- Get the queue transfer method.
Parameters:
s string method name
Returns: method code
Referenced by dts_loadConfigFile().
char* dts_cfgQMethodStr (int method)
Convert method type to string name.
DTS_CFGQMETHODSTR -- Convert method type to string name.
Parameters:
method method type code
Returns: nothing
Referenced by dts_printQueueCfg(), dts_queueProcess(), and dts_xferFile().
int dts_cfgQMode (char * s)
Get the trander mode (push or pull).
DTS_CFGQMODE -- Get the trander mode (push or pull).
Parameters:
s string mode name
Returns: nothing
Referenced by dts_loadConfigFile().
char* dts_cfgQModeStr (int mode)
Convert mode type to string name.
DTS_CFGMODESTR -- Convert mode type to string name
Parameters:
mode mode type code
Returns: nothing
Referenced by dts_printQueueCfg(), and dts_queueProcess().
int dts_cfgQNode (char * s)
Get the node type of queue.
DTS_CFGQNODE -- Get the node type of queue.
Parameters:
s string name of queue
Returns: queue type
Referenced by dts_loadConfigFile().
char* dts_cfgQNodeStr (int node)
Convert dode to type string name.
DTS_CFGQNODESTR -- Convert node to type string name
Parameters:
node queue node code
Returns: nothing
Referenced by dts_nodeStat().
int dts_cfgQType (char * s)
Get the type of queue.
DTS_CFGQTYPE -- Get the type of queue.
Parameters:
s string name of queue
Returns: queue type
Referenced by dts_loadConfigFile().
char* dts_cfgQTypeStr (int type)
Convert mode to string name.
DTS_CFGQTYPESTR -- Convert mode to string name
Parameters:
type queue type code
Returns: nothing
Referenced by dts_printQueueCfg().
time_t dts_cfgStartTime (char * tstr)
Get a timing interval (in sec) from the config value.
DTS_CFGSTARTTIME -- Convert a start time to equivalent time_t seconds.
Parameters:
tstr start time value (string type)
Returns: interval in seconds
Referenced by dts_loadConfigFile().
char* dts_fmtConfig (DTS * dts)
DTS_FMTCONFIG -- Print Config file info as a formatted string.
Referenced by dts_Cfg().
char* dts_getLocalRoot (void)
Utility routine to get values for the local DTS host.
Referenced by dts_sandboxPath().
int dts_getQPort (DTS * dts, char * qname, int tport)
DTS_GETQPORT -- Get the next available base port for a transfer queue. If the input port number is already in use we'll search for a new port to use, otherwise we return the input port (i.e. validate it).
References dtsErrLog().
Referenced by dts_loadConfigFile(), and dts_validateQueue().
void dts_loadConfigDir (DTS * dts, char * cfg, char * dhost, int dport, char * droot, int initialize)
Load the DTS configuration file.
DTS_LOADCONFIGDIR -- Load the DTS configuration files in a directory.
Parameters:
dts DTS struct pointer
cfg DTS config directory
dhost DTS daemon host machine
dport DTS daemon port number
droot DTS daemon root directory
initialize initialize DTS?
Returns: nothing
References dts_isDir(), dts_loadConfigFile(), and dtsLog().
Referenced by dtsInit().
void dts_loadConfigFile (DTS * dts, char * cfg, char * dhost, int dport, char * droot, int initialize)
Load the DTS configuration file.
DTS_LOADCONFIGFILE -- Load the DTS configuration file.
Parameters:
dts DTS struct pointer
cfg DTS config file
dhost DTS daemon host machine
dport DTS daemon port number
droot DTS daemon root directory
initialize initialize DTS?
Returns: nothing
References dts_cfgInterval(), dts_cfgQMethod(), dts_cfgQMode(), dts_cfgQNode(), dts_cfgQType(), dts_cfgStartTime(), dts_getLocalIP(), dts_getQPort(), dts_loadDefaultConfig(), dts_newQueue(), dts_printConfig(), dts_printQPorts(), dts_resolveHost(), dts_semInitId(), dts_testDeliveryDir(), dts_validateQueue(), dtsGets(), and dtsLog().
Referenced by dts_loadConfigDir(), and dtsInit().
int dts_loadDefaultConfig (DTS * dts, char * host, int port)
DTS_LOADDEFAULTCONFIG -- Duh
References dts_getLocalHost(), and dts_resolveHost().
Referenced by dts_loadConfigFile().
char* dts_nameToHost (DTS * dts, char * name)
Convert a DTS name to the host.
DTS_NAMETOHOST -- Convert a DTS name to the host.
Parameters:
dts DTS struct pointer
name DTS name string
Returns: host name
Referenced by dts_resolveHost().
char* dts_nameToIP (DTS * dts, char * name)
Convert a DTS name to the host IP.
DTS_NAMETOIP -- Convert a DTS name to the host IP.
Parameters:
dts DTS struct pointer
name DTS name string
Returns: IP string
References dts_resolveHost().
dtsQueue* dts_newQueue (DTS * dts)
DTS_NEWQUEUE -- Get a new DTS queue structure and fill in the defaults.
References dts_getLocalHost().
Referenced by dts_loadConfigFile().
void dts_printConfig (DTS * dts)
DTS_PRINTCONFIG -- Print Config file info.
Referenced by dts_loadConfigFile().
void dts_printQPorts (DTS * dts)
DTS_GETQPORT -- Get the next available base port for a transfer queue. If the input port number is already in use we'll search for a new port to use, otherwise we return the input port (i.e. validate it).
Referenced by dts_loadConfigFile().
int dts_validateQueue (DTS * dts, dtsQueue * dtsq)
DTS_VALIDATEQUEUE -- Validate the queue structure.
References dts_getQPort().
Referenced by dts_loadConfigFile().
int dts_validPasswd (DTS * dts, char * passwd)
Validate a passwd against the host.
DTS_VALIDPASSWD -- Validate a passwd against the host.
Parameters:
dts DTS struct pointer
passwd passwd to be checked
Returns: nothing
Referenced by dts_abortDTS(), dts_Delete(), and dts_shutdownDTS().
char* dtsGets (char * s, int len, FILE * fp)
DTSGETS A smart fgets() function
Read the line; unlike fgets(), we read the entire line but dump characters that go past the end of the buffer. We accept CR, LF, or CR LF for the line endings to be `safe`.
Parameters:
s string buffer
len length of buffer
fp file descriptor
Returns: pointer to next string on the stream
Referenced by dts_loadConfigFile(), dts_loadControl(), dts_loadDeliveryParams(), and dts_queueComplete().