dtsDeliver.c File Reference
DTS procedures to `deliver` a transfer object.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include <fcntl.h>
#include <ctype.h>
#include <stdarg.h>
#include <sys/param.h>
#include <sys/types.h>
#include <sys/wait.h>
#include `dts.h`
Defines
#define DEBUG (dts&&dts $\rightarrow$ debug)
#define VDEBUG (dts&&dts $\rightarrow$ debug>2)
#define MAXTRIES 3
Functions
char * dts_Deliver (dtsQueue *dtsq, Control *ctrl, char *fpath, int *stat)
Deliver a file at a destination location.
char * dts_getDeliveryPath (dtsQueue *dtsq, Control *ctrl)
Get the delivery path name.
void dts_loadDeliveryParams (Control *ctrl, char *pfname)
Load the delivery app parameters.
int dts_testDeliveryDir (char *dpath, int create, char *msg)
Test the delivery directory.
int dts_validateDelivery (Control *ctrl, char *dpath)
Verify the delivered file.
int dts_addControlHistory (Control *ctrl, char *msg)
Add history record to control file.
int dts_sysExec (char *ewd, char *cmd)
Execute a general UNIX command passed as a string.
int dts_Await (int pid)
Wait for an asynchronous child process to terminate.
void dts_Interrupt (int value)
void dts_Enbint (SIGFUNC handler)
Variables
DTS * dts
int dts_monitor
Detailed Description
DTS procedures to `deliver` a transfer object.
DTSDELIVER.C -- DTS procedures to `deliver` a transfer object.
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
int dts_addControlHistory (Control * ctrl, char * msg)
Add history record to control file.
DTS_ADDCONTROLHISTORY -- Add history record to control file.
Parameters:
ctrl transfer control strucure
msg NULL or an error message
References dts_localTime(), and dts_sandboxPath().
Referenced by dts_Deliver(), and dts_Ingest().
int dts_Await (int pid)
Wait for an asynchronous child process to terminate.
DTS_AWAIT -- Wait for an asynchronous child process to terminate.
Parameters:
pid process ID
References dts_Enbint(), dts_Interrupt(), and dtsLog().
Referenced by dts_sysExec().
char* dts_Deliver (dtsQueue * dtsq, Control * ctrl, char * fpath, int * stat)
Deliver a file at a destination location.
DTS_DELIVER -- Deliver a file at a destination location.
Parameters:
dtsq DTS queue structure
ctrl Transfer control structure
fpath path to the file in spool dir
stat delivery application status
Returns:
References dts_addControlHistory(), dts_fileCopy(), dts_fmtQueueCmd(), dts_getDeliveryPath(), dts_loadDeliveryParams(), dts_localDelete(), dts_qstatDlvrEnd(), dts_qstatDlvrStart(), dts_qstatDlvrStat(), dts_queueNameFmt(), dts_semSetVal(), dts_sysExec(), and dtsLog().
Referenced by dts_endTransfer().
void dts_Enbint (SIGFUNC handler)
DTS_ENBINT -- Post an exception handler function to be executed if any sort of interrupt occurs.
Referenced by dts_Await(), and dts_sysExec().
char* dts_getDeliveryPath (dtsQueue * dtsq, Control * ctrl)
Get the delivery path name.
DTS_GETDELIVERYPATH -- Get the delivery path name.
Parameters:
dtsq queue structure
ctrl control structure
Returns: nothing
Referenced by dts_Deliver(), and dts_fmtQueueCmd().
void dts_Interrupt (int value)
DTS_INTERRUPT -- Exception handler, called if an interrupt is received
Referenced by dts_Await().
void dts_loadDeliveryParams (Control * ctrl, char * pfname)
Load the delivery app parameters.
DTS_LOADDELIVERYPARAMS -- Load the delivery app parameters.
Parameters:
ctrl control structure
pfname path to the delivery parameters file
Returns: nothing
References dtsGets().
Referenced by dts_Deliver(), and dts_Ingest().
int dts_sysExec (char * ewd, char * cmd)
Execute a general UNIX command passed as a string.
DTS_SYSEXEC -- Execute a general UNIX command passed as a string. The command may contain i/o redirection metacharacters. The full path of the command to be executed should be given.
Parameters:
ewd effective working directory
cmd command string to be executed
References dts_Await(), dts_Enbint(), dtsErrLog(), and dtsLog().
Referenced by dts_Deliver(), dts_execCmd(), and dts_Ingest().
int dts_testDeliveryDir (char * dpath, int create, char * msg)
Test the delivery directory.
DTS_TESTDELIVERYDIR -- Test the delivery directory.
Parameters:
dpath path to the delivery directory
create create directory if it doesn't exist?
msg return message string
Referenced by dts_loadConfigFile().
int dts_validateDelivery (Control * ctrl, char * dpath)
Verify the delivered file.
DTS_VALIDATEDELIVERY -- Verify the delivered file.
Parameters:
ctrl transfer control strucure
dpath path to the delivery directory