dtsFileUtil.c File Reference
DTS file utilities.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <ctype.h>
#include <dirent.h>
#include <sys/errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/statvfs.h>
#include <sys/mman.h>
#include <fcntl.h>
#include `dts.h`
Defines
#define _GNU_SOURCE
#define _XOPEN_SOURCE 600
#define PATH_MAX 4096
#define DTS_ALLOC_SIZE 4096000
Functions
FILE * dts_fopen (char *fname, char *mode)
Open the named file and return the file descriptor.
int dts_fclose (FILE *fp)
Close the file stream.
int dts_fileOpen (char *fname, int flags)
Open the named file and return the file descriptor.
int dts_fileClose (int fd)
Close the file descriptor.
int dts_fileSync (int fd)
Sync the file descriptor.
int dts_preAlloc (char *fname, long fsize)
Pre-allocate the space for a file.
long dts_fileSize (int fd)
Return the size (in bytes) of the specified file descriptor.
long dts_fileMode (int fd)
Return the protection mode of the specified file descriptor.
long dts_nameSize (char *fname)
Return the size (in bytes) of the specified file descriptor.
long dts_nameMode (char *fname)
Return the protection mode of the specified file descriptor.
int dts_getBuffer (int fd, unsigned char **buf, long chunkSize, int tnum)
Get a buffer of the specified size from the file.
int dts_fileRead (int fd, void *vptr, int nbytes)
Read exactly `n` bytes from a file descriptor.
int dts_fileWrite (int fd, void *vptr, int nbytes)
Write exactly `n` bytes to a file descriptor.
int dts_fileCopy (char *in, char *out)
Copy and input file to an output file.
int dts_isDir (char *path)
Check whether a path represents a directory.
int dts_isLink (char *path)
Check whether a path represents a symbolic link.
char * dts_readLink (char *ipath)
Read the target of a symlink.
int dts_makePath (char *path, int isDir)
Create the specified path, one directory at a time.
char * dts_pathDir (char *path)
Return the directory portion of a file pathname.
char * dts_pathFname (char *path)
Return the filename portion of a file pathname.
long dts_du (char *filename)
Return the size of a file or directory path in bytes.
int dts_unlink (char *dir, int recurse, char *template)
Remove all matching file in a directory (tree).
long dts_dirSize (char *dir, char *template)
Get the cumulative size of all files in a directory tree.
int dts_dirCopy (char *in, char *out)
Recursively copy a directory to a new location.
int dts_statvfs (char *dir, struct statvfs *fs)
Detailed Description
DTS file utilities.
DTS File Utilities
dts_fileOpen (char *fname, int flags) dts_fileClose (int fd) dts_preAlloc (char *fname, long fsize) dts_fileSize (int fd) dts_fileMode (int fd) dts_nameSize (char *fname) dts_nameMode (char *fname) dts_getBuffer (int fd, unsigned char **buf, long chunkSize, int tnum) dts_fileRead (int fd, void *vptr, int nbytes) dts_fileWrite (int fd, void *vptr, int nbytes) dts_fileCopy (char *in, char *out) dts_isDir (char *path) dts_isLink (char *path) dts_makePath (char *path, int isDir) dts_pathDir (char *path) dts_pathFname (char *path) dts_du (char *filename) dts_unlink (char *dir, int recurse, char *template) dts_dirSize (char *dir, char *template) dts_dirCopy (char *in, char *out) dts_statfs (char *dir, struct statfs *fs)
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
int dts_dirCopy (char * in, char * out)
Recursively copy a directory to a new location.
DTS_DIRCOPY -- Recursively copy a directory to a new location, preserving symlinks and file permissions.
Parameters:
in input directory to copy
out output directory path
Returns: status
References dts_fileCopy().
Referenced by dts_fileCopy().
long dts_dirSize (char * dir, char * template)
Get the cumulative size of all files in a directory tree.
DTS_DIRSIZE -- Get the cumulative size of all files in a directory tree.
Parameters:
dir directory to size
template file-matching template
Returns: status
References dts_patMatch().
long dts_du (char * filename)
Return the size of a file or directory path in bytes.
DTS_DU -- A simple 'du' function for a file or directory tree.
Parameters:
filename filename to be checked
Returns: size of file
References dts_readLink().
Referenced by dts_FSize(), dts_hostInitTransfer(), dts_hostQueueAccept(), dts_hostTo(), and dts_queueInitControl().
int dts_fclose (FILE * fp)
Close the file stream.
DTS_FCLOSE -- Close the file stream.
Parameters:
fp file stream to close
Returns: status
Referenced by dts_loadControl(), dts_logControl(), dts_queueGetCurrent(), dts_queueGetNext(), dts_queueGetStats(), dts_queueSetCurrent(), dts_queueSetNext(), dts_queueSetStats(), and dts_saveControl().
int dts_fileClose (int fd)
Close the file descriptor.
DTS_FILECLOSE -- Close the file descriptor.
Parameters:
fd file descriptor to close
Returns: nothing
Referenced by psSendFile(), and udtSendFile().
int dts_fileCopy (char * in, char * out)
Copy and input file to an output file.
DTS_FILECOPY -- Copy and input file to an output file.
Parameters:
in input file path
out output file path
Returns: number of bytes written
define DTS_MMAP_COPY
References dts_dirCopy(), dts_fileSize(), and dts_isDir().
Referenced by dts_Deliver(), and dts_dirCopy().
long dts_fileMode (int fd)
Return the protection mode of the specified file descriptor.
DTS_FILEMODE - Return the protection mode of the specified file descriptor.
Parameters:
fd file descriptor
Returns: file mode
int dts_fileOpen (char * fname, int flags)
Open the named file and return the file descriptor.
DTS_FILEOPEN -- Open the named file and return the file descriptor.
Parameters:
fname file name to open
flags file open flags
Returns: file descriptor
Referenced by psReceiveFile(), psSendFile(), udtReceiveFile(), and udtSendFile().
int dts_fileRead (int fd, void * vptr, int nbytes)
Read exactly `n` bytes from a file descriptor.
DTS_FILEREAD -- Read exactly `n` bytes from a file descriptor.
Parameters:
fd file descriptor
vptr data buffer to be written
nbytes number of bytes to write
Returns: number of bytes written
Referenced by dts_Cat(), dts_Read(), psSendFile(), and udtSendFile().
long dts_fileSize (int fd)
Return the size (in bytes) of the specified file descriptor.
DTS_FILESIZE - Return the size (in bytes) of the specified file descriptor.
Parameters:
fd file descriptor
Returns: file size
Referenced by dts_fileCopy(), and dts_loadControl().
int dts_fileSync (int fd)
Sync the file descriptor.
DTS_FILESYNC -- Sync the file descriptor.
Parameters:
fd file descriptor to sync to disk
Returns: nothing
int dts_fileWrite (int fd, void * vptr, int nbytes)
Write exactly `n` bytes to a file descriptor.
DTS_FILEWRITE -- Write exactly `n` bytes to a file descriptor.
Parameters:
fd file descriptor
vptr data buffer to be written
nbytes number of bytes to write
Returns: number of bytes written
References dts_setNonBlock().
Referenced by dts_hostFGet(), psReceiveFile(), and udtReceiveFile().
FILE* dts_fopen (char * fname, char * mode)
Open the named file and return the file descriptor.
DTS_FOPEN -- Open the named file and return the file descriptor.
Parameters:
fname file name to open
flags file open mode
Returns: FILE * descriptor
References dtsErrLog().
Referenced by dts_loadControl(), dts_logControl(), dts_logXFerStats(), dts_queueGetCurrent(), dts_queueGetNext(), dts_queueGetStats(), dts_queueSetCurrent(), dts_queueSetNext(), dts_queueSetStats(), and dts_saveControl().
int dts_getBuffer (int fd, unsigned char ** buf, long chunkSize, int tnum)
Get a buffer of the specified size from the file.
DTS_GETBUFFER -- Get a buffer of the specified size from the file. Return the number of characters read.
Parameters:
fd file descriptor
buf buffer to create
chunkSize size of transfer chunk (bytes)
tnum thread number
Returns: file size
int dts_isDir (char * path)
Check whether a path represents a directory.
DTS_ISDIR -- Check whether a path represents a directory.
Parameters:
path pathname to be checked
Returns: 1 (one) if path is a directory, 0 (zero) otherise
Referenced by dts_CheckDir(), dts_Delete(), dts_fileCopy(), dts_hostTo(), dts_loadConfigDir(), dts_queueInitControl(), dts_sandboxPath(), dts_wtar(), dts_xferDirTo(), dts_xferFile(), and dtsInit().
int dts_isLink (char * path)
Check whether a path represents a symbolic link.
DTS_ISLINK -- Check whether a path represents a symbolic link.
Parameters:
path pathname to be checked
Returns: 1 (one) if path is a symbolic link, non-zero otherise
Referenced by dts_Ingest(), and dts_sandboxPath().
int dts_makePath (char * path, int isDir)
Create the specified path, one directory at a time.
DTS_MAKEPATH -- Create the specified path, one directory at a time.
Parameters:
path Path to create
isDir Is final element a directory?
Returns: 1 (one) if path can be created
Referenced by psReceiveFile(), psSendFile(), udtReceiveFile(), and udtSendFile().
long dts_nameMode (char * fname)
Return the protection mode of the specified file descriptor.
DTS_NAMEMODE - Return the protection mode of the named file.
Parameters:
fname file name
Returns: file mode
Referenced by dts_Ingest(), dts_xferDirTo(), and dts_xferFile().
long dts_nameSize (char * fname)
Return the size (in bytes) of the specified file descriptor.
DTS_NAMESIZE - Return the size (in bytes) of the named file.
Parameters:
fname file name
Returns: file size
Referenced by dts_Ingest(), and dts_xferDirTo().
char* dts_pathDir (char * path)
Return the directory portion of a file pathname.
DTS_PATHDIR -- Return the directory portion of a file pathname.
Parameters:
path long path name
Returns: parent directory
Referenced by dts_hostFrom(), dts_hostTo(), dts_queueInitControl(), dts_xferDirFrom(), and dts_xferDirTo().
char* dts_pathFname (char * path)
Return the filename portion of a file pathname.
DTS_PATHFNAME -- Return the filename portion of a file pathname.
Parameters:
path long path name
Returns: filename
Referenced by dts_hostFrom(), dts_hostTo(), dts_queueInitControl(), dts_queueProcess(), dts_xferDirFrom(), and dts_xferDirTo().
int dts_preAlloc (char * fname, long fsize)
Pre-allocate the space for a file.
DTS_PREALLOC -- Pre-allocate the space for a file.
Parameters:
fname file name to create
fsize size of the file
Returns: status code
Referenced by dts_localPrealloc(), dts_Prealloc(), psReceiveFile(), and udtReceiveFile().
char* dts_readLink (char * ipath)
Read the target of a symlink.
DTS_READLINK -- Read the target of a symlink.
Parameters:
ipath input pathname to link
Returns: path to target of symlink
Referenced by dts_du(), dts_Ingest(), and dts_sandboxPath().
int dts_unlink (char * dir, int recurse, char * template)
Remove all matching file in a directory (tree).
DTS_UNLINK -- Remove all matching files in a directory or directory tree. We chdir to each directory to minimize path searches.
Parameters:
dir directory to remove
recurse descend into subdirs?
template file-matching template
Returns: status
References dts_patMatch().
Referenced by dts_Delete(), dts_localDelete(), and dts_queueDelete().