dtsIngest.c File Reference
DTS procedures to `ingest` a transfer object.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include <fcntl.h>
#include <ctype.h>
#include <stdarg.h>
#include <sys/param.h>
#include <sys/wait.h>
#include `dts.h`
#include `dtsdb.h`
Defines
#define DEBUG (dts&&dts $\rightarrow$ debug)
#define VDEBUG (dts&&dts $\rightarrow$ debug>2)
Functions
char * dts_Ingest (dtsQueue *dtsq, Control *ctrl, char *fpath, char *cpath, int *stat)
Ingest a file for transport.
Variables
DTS * dts
int dts_monitor
Detailed Description
DTS procedures to `ingest` a transfer object.
DTSINGEST.C -- DTS procedures to `ingest` a transfer object.
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
char* dts_Ingest (dtsQueue * dtsq, Control * ctrl, char * fpath, char * cpath, int * stat)
Ingest a file for transport.
DTS_INGEST -- Ingest a file for transport.
Parameters:
dtsq DTS queue structure
ctrl Transfer control structure
fpath path to the file in spool dir
cpath path to the control file in spool dir
stat status of the ingest application
Returns: NULL or error message
References dts_addControlHistory(), dts_fmtQueueCmd(), dts_isLink(), dts_loadDeliveryParams(), dts_nameMode(), dts_nameSize(), dts_qstatDlvrEnd(), dts_qstatDlvrStart(), dts_qstatDlvrStat(), dts_readLink(), dts_saveControl(), dts_semSetVal(), dts_sysExec(), dtsErrLog(), and dtsLog().
Referenced by dts_endTransfer().