dtsLog.c File Reference
DTS logging interface.
#include <stdio.h>
#include <fcntl.h>
#include <signal.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <pthread.h>
#include <errno.h>
#include `dts.h`
#include `dtsdb.h`
Defines
#define SZ_FMTSPEC 25
#define SZ_ARGVAL 128
#define EOS 0
#define TY_INT 0
#define TY_DOUBLE 1
#define TY_CHAR 2
#define SZ_ERRBUF (4*SZ_LINE)
Functions
void dtsLog (DTS *dts, char *format,...)
DTS message logger.
void dtsLogMsg (DTS *dts, int key, char *format,...)
Log DTS messages to DTSMON and local database.
void dtsLogStat (DTS *dts, char *msg)
DTS message logger.
void dtsErrLog (dtsQueue *dtsq, char *format,...)
DTS message logger.
void dtsTimeLog (char *fmt, struct timeval t1)
DTS timing message logger.
void dts_encodeString (char *buf, char *format, va_list *argp)
Detailed Description
DTS logging interface.
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
We can log to a local file as well as to a remote monitoring application.
Function Documentation
void dts_encodeString (char * buf, char * format, va_list * argp)
DTS_ENCODESTRING -- Process the format to the output file, taking arguments from the list pointed to by argp as % format specs are encountered in the input.
Parameters:
buf formatted output buffer
format format string
argp variable-length arguments
Returns:
Referenced by dtsErrLog(), dtsLog(), and dtsLogMsg().
void dtsErrLog (dtsQueue * dtsq, char * format, ...)
DTS message logger.
DTS_ERRLOG -- DTS message logger.
Parameters:
dtsq queue pointer to save error msg (or NULL)
format message format string
Returns: nothing
References dts_encodeString(), and dtsLog().
Referenced by dts_endTransfer(), dts_fopen(), dts_getHostByName(), dts_getQPort(), dts_Ingest(), dts_openServerSocket(), dts_queueProcess(), dts_sockRead(), dts_sockWrite(), dts_sysExec(), dts_udtRead(), dts_udtWrite(), dts_xferDirFrom(), dts_xferDirTo(), dts_xferFile(), dts_xferPullFile(), dts_xferPushFile(), psComputeStripe(), psReceiveFile(), psReceiveStripe(), psSendFile(), psSendStripe(), psSpawnThreads(), udtReceiveFile(), udtSendFile(), udtSendStripe(), and udtSpawnThreads().
void dtsLog (DTS * dts, char * format, ...)
DTS message logger.
DTS_LOG -- DTS message logger.
Parameters:
dts DTS struct pointer
format message format string
Returns: nothing
References dts_closeClient(), dts_encodeString(), dts_getClient(), and dts_nullResponse().
Referenced by dts_Access(), dts_Await(), dts_Cat(), dts_Cfg(), dts_CheckDir(), dts_Checksum(), dts_Chmod(), dts_Copy(), dts_Cwd(), dts_Delete(), dts_Deliver(), dts_DestDir(), dts_Dir(), dts_DiskFree(), dts_DiskUsed(), dts_Echo(), dts_endTransfer(), dts_FMode(), dts_FSize(), dts_FTime(), dts_getNextQueueDir(), dts_hostFrom(), dts_hostInitTransfer(), dts_hostTo(), dts_Ingest(), dts_initTransfer(), dts_loadConfigDir(), dts_loadConfigFile(), dts_loadControl(), dts_Mkdir(), dts_monAttach(), dts_monConsole(), dts_monDetach(), dts_pauseQueue(), dts_Ping(), dts_PingSleep(), dts_PingStr(), dts_Prealloc(), dts_qstatSummary(), dts_queueAccept(), dts_queueCleanup(), dts_queueComplete(), dts_queueDelete(), dts_queueDest(), dts_queueProcess(), dts_queueSetControl(), dts_queueSrc(), dts_queueValid(), dts_Read(), dts_remotePing(), dts_Rename(), dts_Set(), dts_SetDbg(), dts_SetRoot(), dts_shutdownQueue(), dts_sigHandler(), dts_startQueue(), dts_Stat(), dts_stopQueue(), dts_sysExec(), dts_Touch(), dts_UnsetDbg(), dts_verifyDTS(), dts_xferPullFile(), dts_xferPushFile(), dts_xferReceiveFile(), dts_xferSendFile(), dtsDaemonize(), dtsErrLog(), dtsErrorExit(), dtsErrorWarn(), psReceiveFile(), udtReceiveFile(), udtReceiveStripe(), and udtSendFile().
void dtsLogMsg (DTS * dts, int key, char * format, ...)
Log DTS messages to DTSMON and local database.
DTS_LOGMSG -- DTS message logger. Log to DTSMON and local database.
Parameters:
dts DTS struct pointer
key DB record key
format message format string
Returns: nothing
References dts_closeClient(), dts_encodeString(), dts_getClient(), and dts_nullResponse().
void dtsLogStat (DTS * dts, char * msg)
DTS message logger.
DTS_LOGSTAT -- DTS stat logger.
Parameters:
dts DTS struct pointer
msg message string
Returns: nothing
References dts_closeClient(), dts_getClient(), and dts_nullResponse().
void dtsTimeLog (char * fmt, struct timeval t1)
DTS timing message logger.
DTSTIMELOG -- DTS timing message logger.
Parameters:
format message format string (must include single 'g' format)
t1 starting time struct
Returns: nothing
Referenced by psReceiveFile(), psReceiveStripe(), psSendFile(), psSendStripe(), udtReceiveFile(), udtSendFile(), and udtSendStripe().