dtsLocal.c File Reference
DTS Command Interface.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <dirent.h>
#include <ctype.h>
#include <utime.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/time.h>
#include <fcntl.h>
#include <xmlrpc-c/base.h>
#include <xmlrpc-c/client.h>
#include <xmlrpc-c/server.h>
#include <xmlrpc-c/server_abyss.h>
#include `dts.h`
#include `dtsMethods.h`
Functions
int dts_localAccess (char *path, int mode)
Check a local file for an access mode.
int dts_localCopy (char *old, char *new)
Copy a local file.
char * dts_localCwd ()
Get the current working directory.
int dts_localDelete (char *path, int recurse)
Delete a local file.
char * dts_localDir (char *path, int lsLong)
Get a local directory listing.
int dts_localChmod (char *path, mode_t mode)
Change the mode of a local file.
int dts_localMkdir (char *path)
Make a local directory.
int dts_localMtime (char *path, long mtime)
Update file modification time.
int dts_localRename (char *old, char *new)
Rename a local file.
int dts_localTouch (char *path)
Touch a local file.
int dts_localPrealloc (char *path, int size)
Pre-allocate a local file.
Variables
DTS * dts
Detailed Description
DTS Command Interface.
DTS Local I/O Interface - Local operations
File Operations:
access <path> <mode> - check file access cwd - get current working directory del <pattern> <pass> <recur> - delete a file dir <pattern> - get a directory listing diskFree - how much disk space is available? diskUsed - how much disk space is used? echo <str> - simple echo function fsize <fname> - get a file size ftime <fname> - get a file time mkdir <path> - make a directory mtime <path> <tm> - set file modification time ping - simple aliveness test function prealloc <fname> <nbytes> - preallocate space for a file rename <old> <new> - rename a file stat <fname> - get file stat() info setroot <path> - set the root directory of a DTS touch <path> - touch a file access time
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
int dts_localAccess (char * path, int mode)
Check a local file for an access mode.
DTS_LOCALACCESS -- Check a local file for an access mode.
Parameters:
path file path to check
mode access mode
Returns: status code or errno
int dts_localChmod (char * path, mode_t mode)
Change the mode of a local file.
DTS_LOCALCHMOD -- Change the mode of a local file.
Parameters:
path file name
mode file mode
Returns: status code or errno
int dts_localCopy (char * old, char * new)
Copy a local file.
DTS_LOCALCOPY -- Copy a local file.
Parameters:
old old filename
new new filename
Returns: status code or errno
char* dts_localCwd (void)
Get the current working directory.
DTS_LOCALCWD -- Get the current working directory.
Parameters:
data caller param data
Returns: status code or errno
Referenced by dts_initCopyMode().
int dts_localDelete (char * path, int recurse)
Delete a local file.
DTS_LOCALDELETE -- Delete a local file.
Parameters:
path local file to delete
recurse recursive delete?
Returns: status code or errno
References dts_isTemplate(), and dts_unlink().
Referenced by dts_Deliver().
char* dts_localDir (char * path, int lsLong)
Get a local directory listing.
DTS_LOCALDIR -- Get a local directory listing.
Parameters:
path path to direcory root
lsLong get long directory listing?
Returns: status code or errno
References dts_fmtMode(), dts_isTemplate(), and dts_patMatch().
int dts_localMkdir (char * path)
Make a local directory.
DTS_LOCALMKDIR -- Make a local directory.
Parameters:
path directory path to create
Returns: status code or errno
Referenced by dts_hostFrom(), and dts_xferFile().
int dts_localMtime (char * path, long mtime)
Update file modification time.
DTS_LOCALMtime -- Update file modification time.
Parameters:
path directory path to create
mtime modification time
Returns: status code or errno
int dts_localPrealloc (char * path, int size)
Pre-allocate a local file.
DTS_LOCALPREALLOC -- Pre-allocate a local file.
Parameters:
path filename path to prealloc
size file size
Returns: status code or errno
References dts_preAlloc().
int dts_localRename (char * old, char * new)
Rename a local file.
DTS_LOCALRENAME -- Rename a local file.
Parameters:
old old file name
new new file name
Returns: status code or errno
int dts_localTouch (char * path)
Touch a local file.
DTS_LOCALTOUCH -- Touch a local file.
Parameters:
path filename path to touch
Returns: status code or errno
Referenced by dts_xferFile().