dtsMethods.c File Reference
DTS Command Interface.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <dirent.h>
#include <pthread.h>
#include <ctype.h>
#include <utime.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/types.h>
#include <sys/file.h>
#include <fcntl.h>
#include <xmlrpc-c/base.h>
#include <xmlrpc-c/client.h>
#include <xmlrpc-c/server.h>
#include <xmlrpc-c/server_abyss.h>
#include `dts.h`
#include `dtsdb.h`
#include `dtsMethods.h`
Functions
int dts_initDTS (void *data)
Initialize the DTS.
int dts_shutdownDTS (void *data)
Shut down the DTS.
int dts_abortDTS (void *data)
Immediately exit the DTS.
int dts_nodeStat (void *data)
Return status information for the given node.
int dts_Access (void *data)
Check a file for an access mode.
int dts_Cat (void *data)
Cat a file.
int dts_Checksum (void *data)
Checksum a file.
int dts_Copy (void *data)
Copy a file.
int dts_Cfg (void *data)
Get the current configuration table name.
int dts_Cwd (void *data)
Get the current working directory.
int dts_Delete (void *data)
Delete a file.
int dts_Dir (void *data)
Get a directory listing.
int dts_DestDir (void *data)
Get a directory listing for a queue's delivery dir.
int dts_CheckDir (void *data)
Test whether path is a directory.
int dts_Chmod (void *data)
Change the mode of a file.
int dts_DiskFree (void *data)
Get 1K-block disk space available on specified path.
int dts_DiskUsed (void *data)
Get 1K-block disk space used on specified path.
int dts_Echo (void *data)
Echo the input text.
int dts_FSize (void *data)
Get the file size for remote file.
int dts_FMode (void *data)
Get the file mode for remote file.
int dts_FTime (void *data)
Get the file times for remote file.
int dts_Mkdir (void *data)
Make a directory.
int dts_Ping (void *data)
Is host and DTS alive.
int dts_PingSleep (void *data)
Is host and DTS alive.
int dts_psHandler (void *data)
int dts_nullHandler (void *data)
int dts_PingStr (void *data)
Is host and DTS alive.
int dts_PingArray (void *data)
int dts_remotePing (void *data)
Is remote host and DTS alive.
int dts_Rename (void *data)
Rename a file.
int dts_SetRoot (void *data)
Set the root directory of a DTS.
int dts_SetDbg (void *data)
Set a debug flag on the DTS node machine.
int dts_UnsetDbg (void *data)
Unset a debug flag on the DTS node machine.
int dts_Touch (void *data)
Touch a file.
int dts_Read (void *data)
Read from a file.
int dts_Write (void *data)
Read from a file.
int dts_Prealloc (void *data)
Pre-allocate a file.
int dts_Stat (void *data)
Get the stat() info for a file.
int dts_startQueue (void *data)
Start the named DTS queue.
int dts_shutdownQueue (void *data)
Shut down the named DTS queue.
int dts_flushQueue (void *data)
Flush the named queue.
int dts_pokeQueue (void *data)
int dts_pauseQueue (void *data)
Poke the named queue.
int dts_stopQueue (void *data)
Stop processing of the named queue.
int dts_getQueueStat (void *data)
Get the status flag of the named queue.
int dts_setQueueStat (void *data)
Set the status flag of the named queue.
int dts_setQueueCount (void *data)
Set the pending count of the named queue.
int dts_getQueueCount (void *data)
Get the pending count of the named queue.
int dts_setQueueDir (void *data)
Set the queue deliveryDirectory.
int dts_getQueueDir (void *data)
Get the queue delivery directory.
int dts_setQueueCmd (void *data)
Set the queue deliveryCmd.
int dts_getQueueCmd (void *data)
Get the queue deliveryCmd.
int dts_getCopyDir (void *data)
Get the DTS copy directory.
int dts_execCmd (void *data)
Execute the named command.
int dts_listQueue (void *data)
List pending queue data.
int dts_restartQueue (void *data)
Simply stop, then restart, the queue.
int dts_addToQueue (void *data)
Add the named object to the DTS queue.
int dts_removeFromQueue (void *data)
Remove the named object from the DTS queue.
int dts_printQueueCfg (void *data)
Print queue configuration.
int dts_List (void *data)
List configuration parameters.
int dts_Set (void *data)
Set and option value.
int dts_Get (void *data)
Get and option value.
int dts_queueAccept (void *data)
See if queue will accept a new object.
int dts_queueValid (void *data)
See if queue name is valid on the host.
int dts_queueDest (void *data)
Get the destination of the named queue.
int dts_queueSrc (void *data)
Get the source of the named queue.
int dts_queueComplete (void *data)
Complete transfer of a file.
int dts_queueRelease (void *data)
Release lock on queue semaphore.
int dts_queueSetControl (void *data)
Create the control file for the transfer.
int dts_queueUpdateStats (void *data)
Update queue transfer statistics.
int dts_initTransfer (void *data)
Initialize a transfer operation.
int dts_endTransfer (void *data)
Clean up and terminate a transfer operation.
int dts_doTransfer (void *data)
Do the actual transfer of an object.
int dts_cancelTransfer (void *data)
Cancel an active file transfer.
int dts_testFault (void *data)
Variables
DTS * dts
char * build_version
Detailed Description
DTS Command Interface.
DTS Command Interface - These are the methods implemented for he XML-RPC interace. These command are used from a variety of locations during the operation of the DTS (i.e. the queueing, logging or interactive environments.
initDTS - reinitialize DTS shutdownDTS - shutdown DTS, cancel all queues abortDTS - exit DTS immediately
File Operations:
access <path> <mode> - check file access cwd - get current working directory del <pattern> <pass> <recur> - delete a file dir <pattern> - get a directory listing diskFree - how much disk space is available? diskUsed - how much disk space is used? echo <str> - simple echo function fsize <fname> - get a file size ftime <fname> - get a file time mkdir <path> - make a directory ping - simple aliveness test function sping - simple aliveness test function prealloc <fname> <nbytes> - preallocate space for a file rename <old> <new> - rename a file stat <fname> - get file stat() info setroot <path> - set the root directory of a DTS touch <path> - touch a file access time
Queue Operations:
startQueue - start the named queue stopQueue - stop the named queue flushQueue - flush the named queue listQueue - list pending queue data restartQueue - restart (stop-then-start) queue addToQueue - add object to queue removeFromQueue - delete object from queue printQueueCfg - print queue configuration
queueAccept - accept new object to queue queueValid - See if queue name is valid queueSetControl - Set control file for transfer queueTrace - trace connectivity through a queue queueUpdateStats - update queue statistics
list <option> - list config parameters set <option>
- set a specified option get <option> - get value of option
initTransfer <method> - initialize an object transfer doTransfer - transfer the actual file endTransfer - end the object transfer cancelTransfer - abort an in-progress transfer
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
int dts_abortDTS (void * data)
Immediately exit the DTS.
DTS_ABORTDTS -- Immediately exit the DTS daemon.
Parameters:
data caller param data
Returns: status code or errno
References dts_validPasswd().
int dts_Access (void * data)
Check a file for an access mode.
DTS_ACCESS -- Check a file for an access mode.
Parameters:
data caller param data
Returns: status code or errno
References dts_sandboxPath(), and dtsLog().
int dts_addToQueue (void * data)
Add the named object to the DTS queue.
DTS_ADDTOTQUEUE -- Add the named object to the DTS queue.
Parameters:
data caller param data
Returns: status code or errno
int dts_cancelTransfer (void * data)
Cancel an active file transfer.
DTS_CANCELTRANSFER -- Cancel an active file transfer.
Parameters:
data caller param data
Returns: status code or errno
int dts_Cat (void * data)
Cat a file.
DTS_CAT -- Cat a file.
Parameters:
data caller param data
Returns: status code or errno
References base64_encode(), dts_fileRead(), dts_sandboxPath(), and dtsLog().
int dts_Cfg (void * data)
Get the current configuration table name.
DTS_CFG -- Get the current configuration table name.
Parameters:
data caller param data
Returns: status code or errno
References dts_fmtConfig(), and dtsLog().
int dts_CheckDir (void * data)
Test whether path is a directory.
DTS_CHECKDIR -- Test whether path is a directory.
Parameters:
data caller param data
Returns: status code or errno
References dts_isDir(), dts_sandboxPath(), and dtsLog().
int dts_Checksum (void * data)
Checksum a file.
DTS_CHECKSUM -- Checksum a file.
Parameters:
data caller param data
Returns: status code or errno
References dts_sandboxPath(), and dtsLog().
int dts_Chmod (void * data)
Change the mode of a file.
DTS_CHMOD -- Change the mode of a file.
Parameters:
data caller param data
Returns: status code or errno
References dts_sandboxPath(), and dtsLog().
int dts_Copy (void * data)
Copy a file.
DTS_COPY -- Copy a file.
Parameters:
data caller param data
Returns: status code or errno
References dts_sandboxPath(), and dtsLog().
int dts_Cwd (void * data)
Get the current working directory.
DTS_CWD -- Get the current working directory.
Parameters:
data caller param data
Returns: status code or errno
References dtsLog().
int dts_Delete (void * data)
Delete a file.
DTS_DEL -- Delete a file.
Parameters:
data caller param data
Returns: status code or errno
References dts_isDir(), dts_isTemplate(), dts_sandboxPath(), dts_unlink(), dts_validPasswd(), and dtsLog().
int dts_DestDir (void * data)
Get a directory listing for a queue's delivery dir.
DTS_DESTDIR -- Get a directory listing for a queue's delivery dir.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup(), and dtsLog().
int dts_Dir (void * data)
Get a directory listing.
DTS_DIR -- Get a directory listing.
Parameters:
data caller param data
Returns: status code or errno
References dts_fmtMode(), dts_isTemplate(), dts_patMatch(), dts_sandboxPath(), and dtsLog().
int dts_DiskFree (void * data)
Get 1K-block disk space available on specified path.
DTS_DISKFREE -- Get disk space available on specified path.
Parameters:
data caller param data
Returns: status code or errno
References dts_sandboxPath(), and dtsLog().
int dts_DiskUsed (void * data)
Get 1K-block disk space used on specified path.
DTS_DISKUSED -- Get disk space used on specified path.
Parameters:
data caller param data
Returns: status code or errno
References dts_sandboxPath(), and dtsLog().
int dts_doTransfer (void * data)
Do the actual transfer of an object.
DTS_DOTRANSFER -- Do the actual transfer of an object.
Parameters:
data caller param data
Returns: status code or errno
int dts_Echo (void * data)
Echo the input text.
DTS_ECHO -- Simple echo function.
Parameters:
data caller param data
Returns: status code or errno
References dtsLog().
int dts_endTransfer (void * data)
Clean up and terminate a transfer operation.
DTS_ENDTRANSFER -- Clean up and terminate a transfer operation.
Parameters:
data caller param data
Returns: status code or errno
References dts_Deliver(), dts_Ingest(), dts_loadControl(), dts_logXFerStats(), dts_qstatDiskEnd(), dts_qstatDiskStart(), dts_qstatDlvrStat(), dts_qstatEnd(), dts_qstatSetFName(), dts_qstatSummary(), dts_queueDelete(), dts_queueGetCurrent(), dts_queueLookup(), dts_queueNameFmt(), dts_queueSetCurrent(), dts_sandboxPath(), dts_semIncr(), dtsErrLog(), dtsLog(), transferMB(), and transferMb().
int dts_execCmd (void * data)
Execute the named command.
DTS_EXECCMD -- Execute the named command.
Parameters:
data caller param data
Returns: status code or errno
References dts_sysExec().
int dts_flushQueue (void * data)
Flush the named queue.
DTS_FLUSHQUEUE -- Set current to next, which is used to skip over files.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueGetCurrent(), dts_queueGetNext(), dts_queueLookup(), and dts_queueSetCurrent().
int dts_FMode (void * data)
Get the file mode for remote file.
DTS_FMODE -- Get the file mode for remote file.
Parameters:
data caller param data
Returns: status code or errno
References dts_sandboxPath(), and dtsLog().
int dts_FSize (void * data)
Get the file size for remote file.
DTS_FSIZE -- Get the file size for remote file.
Parameters:
data caller param data
Returns: status code or errno
References dts_du(), dts_sandboxPath(), and dtsLog().
int dts_FTime (void * data)
Get the file times for remote file.
DTS_FTIME -- Get the file access/create/modify time for remote file.
Parameters:
data caller param data
Returns: status code or errno
References dts_sandboxPath(), and dtsLog().
int dts_Get (void * data)
Get and option value.
DTS_GET - Get an option value.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup().
int dts_getCopyDir (void * data)
Get the DTS copy directory.
DTS_GETCOPYDIR -- Get the DTS copy directory.
Parameters:
data caller param data
Returns: status code or errno
int dts_getQueueCmd (void * data)
Get the queue deliveryCmd.
DTS_GETQUEUECMD -- Get the queue deliveryCmd.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup().
int dts_getQueueCount (void * data)
Get the pending count of the named queue.
DTS_GETQUEUECOUNT -- Get the pending count of the named queue.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup(), and dts_semGetVal().
int dts_getQueueDir (void * data)
Get the queue delivery directory.
DTS_GETQUEUEDIR -- Get the queue delivery directory.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup().
int dts_getQueueStat (void * data)
Get the status flag of the named queue.
DTS_GETQUEUESTAT -- Get the status flag of the named queue.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup(), and dts_semGetVal().
int dts_initDTS (void * data)
Initialize the DTS.
DTS_INITDTS -- (Re-)Initialize the DTS.
Parameters:
data caller param data
Returns: status code or errno
int dts_initTransfer (void * data)
Initialize a transfer operation.
DTS_INITTRANSFER -- Initialize a transfer operation.
Parameters:
data caller param data
Returns: status code or errno
References dts_getNextQueueDir(), dts_getQueuePath(), dts_qstatInit(), dts_qstatStart(), dts_queueLookup(), dts_queueNameFmt(), dts_semGetVal(), and dtsLog().
int dts_List (void * data)
List configuration parameters.
DTS_LIST -- List config parameters.
Parameters:
data caller param data
Returns: status code or errno
int dts_listQueue (void * data)
List pending queue data.
DTS_LISTQUEUE -- List pending queue data.
Parameters:
data caller param data
Returns: status code or errno
int dts_Mkdir (void * data)
Make a directory.
DTS_MKDIR -- Make a directory.
Parameters:
data caller param data
Returns: status code or errno
References dts_sandboxPath(), and dtsLog().
int dts_nodeStat (void * data)
Return status information for the given node.
DTS_NODESTAT - Return status information for the given node.
Parameters:
data caller param data
Returns: status code or errno
References dts_cfgQNodeStr(), dts_queueGetCurrent(), dts_queueGetNext(), dts_queueGetStats(), dts_sandboxPath(), and dts_semGetVal().
int dts_pauseQueue (void * data)
Poke the named queue.
Pause processing of the named queue.
DTS_POKEQUEUE -- Add 1 to current, which is used to skip over files.
Parameters:
data caller param data
Returns: status code or errno
DTS_PAUSEQUEUE -- Stop processing of the named queue.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup(), dts_semGetVal(), dts_semSetVal(), and dtsLog().
int dts_Ping (void * data)
Is host and DTS alive.
DTS_PING -- Simple aliveness test function.
Parameters:
data caller param data
Returns: status code or errno
References dtsLog().
int dts_PingSleep (void * data)
Is host and DTS alive.
DTS_PINGSLEEP -- Simple aliveness test function.
Parameters:
data caller param data
Returns: status code or errno
NOTE: This is an ASYNC method.
References dts_closeClient(), dts_getClient(), and dtsLog().
int dts_PingStr (void * data)
Is host and DTS alive.
DTS_PINGSTR -- Simple aliveness test function, string return
Parameters:
data caller param data
Returns: status code or errno
DTS_PINGARRAY -- Simple aliveness test function, array return
Parameters:
data caller param data
Returns: status code or errno
References dtsLog().
int dts_Prealloc (void * data)
Pre-allocate a file.
DTS_PREALLOC -- Pre-allocate a file.
Parameters:
data caller param data
Returns: status code or errno
References dts_preAlloc(), dts_sandboxPath(), and dtsLog().
int dts_printQueueCfg (void * data)
Print queue configuration.
DTS_PRINTQUEUECFG -- Print queue configuration.
Parameters:
data caller param data
Returns: status code or errno
References dts_cfgQMethodStr(), dts_cfgQModeStr(), dts_cfgQTypeStr(), and dts_queueLookup().
int dts_queueAccept (void * data)
See if queue will accept a new object.
DTS_QUEUEACCEPT - See if queue will accept a new object.
Parameters:
data caller param data
Returns: status code or errno
References dts_getNextQueueDir(), dts_getQueuePath(), and dtsLog().
int dts_queueComplete (void * data)
Complete transfer of a file.
DTS_QUEUECOMPLETE - Complete transfer of a file.
Parameters:
data caller param data
Returns: status code or errno
References dts_sandboxPath(), dtsGets(), and dtsLog().
int dts_queueDest (void * data)
Get the destination of the named queue.
DTS_QUEUEDEST -- Get the destination of the named queue.
Parameters:
data caller param data
Returns: status code or errno
References dtsLog().
int dts_queueRelease (void * data)
Release lock on queue semaphore.
DTS_QUEUERELEASE -- Release lock on queue semaphore.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup(), and dts_semSetVal().
int dts_queueSetControl (void * data)
Create the control file for the transfer.
DTS_QUEUESETCONTROL - Create the control file for the transfer.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup(), dts_queueNameFmt(), dts_sandboxPath(), and dtsLog().
int dts_queueSrc (void * data)
Get the source of the named queue.
DTS_QUEUESRC -- Get the source of the named queue.
Parameters:
data caller param data
Returns: status code or errno
References dtsLog().
int dts_queueUpdateStats (void * data)
Update queue transfer statistics.
DTS_QUEUEUPDATESTATS -- Update queue transfer statistics.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup(), and dts_queueSetStats().
int dts_queueValid (void * data)
See if queue name is valid on the host.
DTS_QUEUEVALID - See if queue name is valid on the host.
Parameters:
data caller param data
Returns: status code or errno
References dtsLog().
int dts_Read (void * data)
Read from a file.
DTS_READ -- Read from a file. We read at most 4096 bytes from the file at a time. On input we get the offset into the file and the requested number of bytes. We update the offset on output and return the number of bytes read as a base-64 encoded string.
Parameters:
data caller param data
Returns: status code or errno
References base64_encode(), dts_fileRead(), dts_sandboxPath(), and dtsLog().
int dts_remotePing (void * data)
Is remote host and DTS alive.
DTS_REMOTEPING -- Simple 3rd party aliveness test function.
Parameters:
data caller param data
Returns: status code or errno
References dts_hostPing(), and dtsLog().
int dts_removeFromQueue (void * data)
Remove the named object from the DTS queue.
DTS_REMOVEFROMQUEUE -- Remove the named object from the DTS queue.
Parameters:
data caller param data
Returns: status code or errno
int dts_Rename (void * data)
Rename a file.
DTS_RENAME -- Rename a file.
Parameters:
data caller param data
Returns: status code or errno
References dts_sandboxPath(), and dtsLog().
int dts_restartQueue (void * data)
Simply stop, then restart, the queue.
DTS_RESTARTQUEUE -- Simply stop, then restart, the queue. We pass through the calling params and don't need to interpret them here.
Parameters:
data caller param data
Returns: status code or errno
References dts_startQueue(), and dts_stopQueue().
int dts_Set (void * data)
Set and option value.
DTS_SET - Set an option value.
Parameters:
data caller param data
Returns: status code or errno
References dtsLog().
int dts_SetDbg (void * data)
Set a debug flag on the DTS node machine.
DTS_SETDBG -- Set a debug flag on the DTS node machine.
Parameters:
data caller param data
Returns: status code or errno
References dtsLog().
int dts_setQueueCmd (void * data)
Set the queue deliveryCmd.
DTS_SETQUEUECMD -- Set the queue deliveryCmd
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup().
int dts_setQueueCount (void * data)
Set the pending count of the named queue.
DTS_SETQUEUECOUNT -- Set the pending count of the named queue.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup(), and dts_semSetVal().
int dts_setQueueDir (void * data)
Set the queue deliveryDirectory.
DTS_SETQUEUEDIR -- Set the queue deliveryDirectory
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup().
int dts_setQueueStat (void * data)
Set the status flag of the named queue.
DTS_SETQUEUESTAT -- Set the status flag of the named queue.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup(), and dts_semSetVal().
int dts_SetRoot (void * data)
Set the root directory of a DTS.
DTS_SETROOT -- Set the root directory of a DTS.
Parameters:
data caller param data
Returns: status code or errno
References dts_initServerRoot(), dts_sandboxPath(), and dtsLog().
int dts_shutdownDTS (void * data)
Shut down the DTS.
DTS_SHUTDOWNDTS -- Shut down the DTS daemon.
Parameters:
data caller param data
Returns: status code or errno
References dts_validPasswd().
int dts_shutdownQueue (void * data)
Shut down the named DTS queue.
DTS_SHUTDOWNQUEUE -- Shutdown the named DTS queue
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup(), dts_semGetVal(), dts_semSetVal(), and dtsLog().
int dts_startQueue (void * data)
Start the named DTS queue.
DTS_STARTQUEUE -- Start the named DTS queue
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup(), dts_semGetVal(), dts_semSetVal(), and dtsLog().
Referenced by dts_restartQueue().
int dts_Stat (void * data)
Get the stat() info for a file.
DTS_STAT -- Get the stat() info for a file.
Parameters:
data caller param data
Returns: status code or errno
References dts_sandboxPath(), and dtsLog().
int dts_stopQueue (void * data)
Stop processing of the named queue.
DTS_STOPQUEUE -- Stop processing of the named queue.
Parameters:
data caller param data
Returns: status code or errno
References dts_queueLookup(), dts_semSetVal(), and dtsLog().
Referenced by dts_restartQueue().
int dts_Touch (void * data)
Touch a file.
DTS_TOUCH -- Touch a file.
Parameters:
data caller param data
Returns: status code or errno
References dts_sandboxPath(), and dtsLog().
int dts_UnsetDbg (void * data)
Unset a debug flag on the DTS node machine.
DTS_UNSETDBG -- Unset a debug flag on the DTS node machine.
Parameters:
data caller param data
Returns: status code or errno
References dtsLog().
int dts_Write (void * data)
Read from a file.
DTS_WRITE -- Write to a file.
Parameters:
data caller param data
Returns: status code or errno