dtsPull.c File Reference
DTS Pull-Model Transfer Methods.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
#include <pthread.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <xmlrpc-c/base.h>
#include <xmlrpc-c/client.h>
#include <xmlrpc-c/server.h>
#include <xmlrpc-c/server_abyss.h>
#include `dts.h`
#include `dtsUDT.h`
#include `dtsPSock.h`
Functions
int dts_nullHandler ()
int dts_xferPullFile (void *data)
Pull a file from the src to the dest machine.
int dts_xferSendFile (void *data)
Send a file from the src to the dest machine.
Variables
DTS * dts
int thread_sem
int queue_delay
Detailed Description
DTS Pull-Model Transfer Methods.
DTS Pull-Model Transfer Methods
The methods defined here are both the client and server-side code needed to implement the `pull` model of data transfer. In this mode, an RPC command is called to pull data from the source to the destination machine. The source machine acts as a server, opening the transfer sockets locally before sending a request to the remote machine to receive the file. Once the connection is established, transfer begins. The return status of this method then determines whether the transfer was successful.
A sequence diagram of the process would look something like:
Pull Model:
QMgr Host A Host B
(1) ----[Pull Msg] ---------------------------------->
(2) Socket setup
(3) <-----[FileSend Msg]------
(4) <=====[Data Transfer]=====>
(5) <----[Status Return]-------
The 'QMgr' is the Queue Manager which initiates the request on the local machine.
RPC Methods Implemented:
dts_xferPullFile initiate Pull transfer of file (dest method) dts_xferSendFile begin sending file (src method)
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
int dts_xferPullFile (void * data)
Pull a file from the src to the dest machine.
DTS_XFERPULL -- Pull a file from the src to the dest machine.
RPC Params: xferId S transfer id method S transfer method fileName S file name fileSize I file size nthreads I num of transfer threads to open srcPort I starting port number destHost S FQDN of destination machine destCmdURL S destination xmlrpc URI
RPC Returns: tsec I transfer time seconds tusec I transfer time micro-seconds status I transfer succeeded (0) or failed (1) ---------------------------------------------------------------------
Parameters:
data caller param data
Returns: status code
References dts_qstatNetEnd(), dts_qstatNetStart(), dts_queueFromPath(), dts_queueNameFmt(), dts_semGetVal(), dts_semInit(), dts_semRemove(), dtsErrLog(), dtsLog(), psCollectThreads(), psReceiveFile(), psSpawnThreads(), transferMB(), transferMb(), udtReceiveFile(), and udtSpawnThreads().
int dts_xferSendFile (void * data)
Send a file from the src to the dest machine.
DTS_XFERSENDFILE -- Send a file to the dest machine.
RPC Params: xferId S transfer id fileName S file name fileSize I file size nthreads I num of transfer threads to open srcPort I starting port number srcIP S IP address of caller (string)
RPC Return: 0 transfer succeeded 1 transfer failed ---------------------------------------------------------------------
Parameters:
data caller param data
Returns: status code
References dts_queueFromPath(), dts_queueNameFmt(), dtsLog(), psCollectThreads(), psSendFile(), psSpawnThreads(), transferMB(), transferMb(), udtSendFile(), and udtSpawnThreads().