dtsPush.c File Reference
DTS Push-Model Transfer Methods.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
#include <pthread.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <xmlrpc-c/base.h>
#include <xmlrpc-c/client.h>
#include <xmlrpc-c/server.h>
#include <xmlrpc-c/server_abyss.h>
#include `dts.h`
#include `dtsUDT.h`
#include `dtsPSock.h`
Functions
int dts_nullHandler ()
int dts_xferPushFile (void *data)
Push a file from the src to the dest machine.
int dts_xferReceiveFile (void *data)
Push a file from the src to the dest machine.
Variables
DTS * dts
int thread_sem
int queue_delay
int first_write
Detailed Description
DTS Push-Model Transfer Methods.
DTS Push-Model Transfer Methods
The methods defined here are both the client and server-side code needed to implement the `push` model of data transfer. In this mode, an RPC command is called to push data from the source to the destination machine. The source machine acts as a server, opening the transfer sockets locally before sending a request to the remote machine to receive the file. Once the connection is established, transfer begins. The return status of this method then determines whether the transfer was successful.
A sequence diagram of the process would look something like:
Push Model:
QMgr Host A Host B
(1) ----[Push Msg] ---------->
(2) Socket setup
(3) ----[FileRecieve Msg]----->
(4) <=====[Data Transfer]=====>
(5) <----[Status Return]-------
The 'QMgr' is the Queue Manager which initiates the request on the local machine.
RPC Methods Implemented:
dts_xferPushFile initiate Push transfer of file (src method) dts_xferReceiveFile begin receiving file (dest method)
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
int dts_xferPushFile (void * data)
Push a file from the src to the dest machine.
DTS_XFERPUSH -- Push a file from the src to the dest machine.
RPC Params: xferId S transfer id method S transfer method fileName S file name fileSize I file size nthreads I num of transfer threads to open srcPort I starting port number destHost S FQDN of destination machine destCmdURL S destination xmlrpc URI
RPC Returns: tsec I transfer time seconds tusec I transfer time micro-seconds status I transfer succeeded (0) or failed (1) ---------------------------------------------------------------------
Parameters:
data caller param data
Returns: status code
References dts_getLocalIP(), dts_queueFromPath(), dts_queueNameFmt(), dts_semGetVal(), dts_semInit(), dts_semRemove(), dtsErrLog(), dtsLog(), psCollectThreads(), psSendFile(), psSpawnThreads(), transferMB(), transferMb(), udtSendFile(), and udtSpawnThreads().
int dts_xferReceiveFile (void * data)
Push a file from the src to the dest machine.
DTS_XFERRECEIVEFILE -- Receive a file on the dest machine.
RPC Params: xferId S transfer id fileName S file name fileSize I file size nthreads I num of transfer threads to open srcPort I starting port number srcIP S IP address of caller (string)
RPC Return: 0 transfer succeeded 1 transfer failed ---------------------------------------------------------------------
Receive a file on the dest machine.
Parameters:
data caller param data
Returns: status code
References dts_qstatNetEnd(), dts_qstatNetStart(), dts_queueFromPath(), dts_queueNameFmt(), dtsLog(), psCollectThreads(), psReceiveFile(), psSpawnThreads(), transferMB(), transferMb(), udtReceiveFile(), and udtSpawnThreads().