dtsPSock.c File Reference
DTS parallel socket transfer routines.
#include <pthread.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <netdb.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <fcntl.h>
#include <sys/errno.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include `dts.h`
#include `dtsPSock.h`
Functions
void dts_printPHdr (char *s, phdr *h)
int psSpawnThreads (void *worker, int nthreads, char *dir, char *fname, long fsize, int mode, int port, char *host, int verbose, pthread_t *tids)
Spawn a worker thread for the transfer.
int * psCollectThreads (int nthreads, pthread_t *tids)
Collect worker threads for the transfer.
void psSendFile (void *data)
Send a file to a remote DTS.
void psReceiveFile (void *data)
Read a file from a remote DTS.
int psSendStripe (int sock, unsigned char *dbuf, long offset, int tnum, long maxbytes)
Do actual transfer of data stripe to the socket.
unsigned char * psReceiveStripe (int sock, long offset, int tnum)
Read data stripe from the socket connection.
void psComputeStripe (long fsize, int nthreads, int tnum, long *chsize, long *start, long *end)
Compute the various parameters of a 'stripe'.
Variables
pthread_mutex_t svc_mutex = PTHREAD_MUTEX_INITIALIZER
int psock_checksum_policy = CS_CHUNK
int err_return = -1
int thread_sem = 0
struct timeval io_tv
int queue_delay
int first_write
DTS * dts
Detailed Description
DTS parallel socket transfer routines.
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
void dts_printPHdr (char * s, phdr * h)
DTS_PRINTHDR -- Debug Utility.
int psCollectThreads (int nthreads, pthread_t * tids)
Collect worker threads for the transfer.
PSCOLLECTTHREADS -- Collect the worker threads for the transfer. Our onl job here is start a thread to rejoin the previously createed threads.
Parameters:
nthreads number of threads to create
tids thread IDs
Returns: status code
Referenced by dts_xferPullFile(), dts_xferPushFile(), dts_xferReceiveFile(), and dts_xferSendFile().
psComputeStripe (long fsize, int nthreads, int tnum, long * chsize, long * start, long * end)
Compute the various parameters of a 'stripe'.
PSCOMPUTESTRIPE -- Compute the parameters of a data stripe given the file size and number of worker threads.
Parameters:
fsize file size
nthreads numbers of threads being processed
tnum this thread number
chsize chunk size
start starting byte number of stripe (output)
end ending byte number of stripe (output)
Returns: nothing
UDTCOMPUTESTRIPE -- Compute the parameters of a data stripe given the file size and number of worker threads.
Parameters:
fsize file size
nthreads numbers of threads being processed
tnum this thread number
chsize chunk size
start starting byte number of stripe (output)
end ending byte number of stripe (output)
Returns: nothing
References dtsErrLog().
Referenced by psSpawnThreads(), and udtSpawnThreads().
psReceiveFile (void * data)
Read a file from a remote DTS.
psReceiveFile -- Receive a file from a remote DTS.
This function can be called to read a portion of a file from a remote host. Arguments are passed in through a generic 'data' pointer to the psArg struct defined for this 'stripe' of the data.
In this procedure, we act as a client in the connection, i.e. the transfer won't begin until we connect to a remote server sending the data.
Parameters:
data caller thread data
Returns: nothing
References dts_fileOpen(), dts_fileWrite(), dts_makePath(), dts_openClientSocket(), dts_openServerSocket(), dts_preAlloc(), dts_sandboxPath(), dts_semDecr(), dtsErrLog(), dtsLog(), dtsTimeLog(), psReceiveStripe(), and svc_mutex.
Referenced by dts_xferPullFile(), and dts_xferReceiveFile().
uchar * psReceiveStripe (int sock, long offset, int tnum)
Read data stripe from the socket connection.
psReceiveStripe -- Do the actual transfer of the data stripe to the client connection. A 'stripe' of data is actually transferred in much smaller 'chunks' which can be tuned to be optimal for the given connection. The checksum policy allows us to perform a checksum of the data either for the entire stripe, or for each individual chunk. The former is generally more efficient as it involves fewer round-trips to the client (i.e. send the checksum and wait for verification before sending next chunk). File-level checksum policy is enforced by our parent.
Parameters:
sock socket descriptor
offset file offset for this stripe
tnum thread (i.e. stripe) number
Returns: a pointer to the data read
References dts_debugLevel(), dts_sockRead(), dts_sockWrite(), dtsErrLog(), dtsTimeLog(), and psock_checksum_policy.
Referenced by psReceiveFile().
psSendFile (void * data)
Send a file to a remote DTS.
psSendFile -- Send a file to a remote DTS.
This function can be called to send a portion of a file to a remote host. Arguments are passed in through a generic 'data' pointer to the psArg struct defined for this 'stripe' of the data.
In this procedure, we act as a server, i.e. we open the specified tcp/ip socket and wait for a client connection before beginning any transfer.
Parameters:
data caller thread data
Returns: nothing
References dts_fileClose(), dts_fileOpen(), dts_fileRead(), dts_makePath(), dts_openClientSocket(), dts_openServerSocket(), dts_sandboxPath(), dts_semDecr(), dtsErrLog(), dtsTimeLog(), psSendStripe(), and svc_mutex.
Referenced by dts_xferPushFile(), and dts_xferSendFile().
int psSendStripe (int sock, unsigned char * dbuf, long offset, int tnum, long maxbytes)
Do actual transfer of data stripe to the socket.
psSendStripe -- Do the actual transfer of the data stripe to the client connection. A 'stripe' of data is actually transferred in much smaller 'chunks' which can be tuned to be optimal for the given connection. The checksum policy allows us to perform a checksum of the data either for the entire stripe, or for each individual chunk. The former is generally more efficient as it involves fewer round-trips to the client (i.e. send the checksum and wait for verification before sending next chunk). File-level checksum policy is enforced by our parent.
Parameters:
sock socket descriptor
dbuf data buffer
offset file offset for this stripe
tnum thread number
maxbytes max bytes to transfer
Returns: number of chunks sent
References dts_debugLevel(), dts_sockRead(), dts_sockWrite(), dtsErrLog(), dtsTimeLog(), and psock_checksum_policy.
Referenced by psSendFile().
int psSpawnThreads (void * worker, int nthreads, char * dir, char * fname, long fsize, int mode, int port, char * host, int verbose, pthread_t * tids)
Spawn a worker thread for the transfer.
PSSPAWNTHREADS -- Spawn a worker thread for the transfer. All we do here is start a thread to run the function passed in. This may be used to either read or write the data.
Parameters:
worker worker function
nthreads number of threads to create
dir working directory
fname file name
fsize file size
mode transfer mode (push or pull)
port client base port number
host client host name
verbose verbose output flag
tids thread id array
Returns: status code
References dtsErrLog(), and psComputeStripe().
Referenced by dts_xferPullFile(), dts_xferPushFile(), dts_xferReceiveFile(), and dts_xferSendFile().
Variable Documentation
int psock_checksum_policy = CS_CHUNK
FIXME -- CS_STRIPE and CS_PACKET not working......
Referenced by dts_sockRead(), dts_sockWrite(), psReceiveStripe(), and psSendStripe().
pthread_mutex_t svc_mutex = PTHREAD_MUTEX_INITIALIZER
Mutex lock for thread startup to protect file I/O.
Referenced by psReceiveFile(), and psSendFile().