dtsQueueUtil.c File Reference
DTS queue utilities.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include <pthread.h>
#include <fcntl.h>
#include <ctype.h>
#include <stdarg.h>
#include <sys/file.h>
#include `dtsPSock.h`
#include `dts.h`
Defines
#define DEBUG (dts&&dts $\rightarrow$ debug)
Functions
dtsQueue * dts_queueLookup (char *qname)
Lookup a DTS queue struct by name.
char * dts_getQueuePath (DTS *dts, char *qname)
Get the path to the spool dir for a given queue.
char * dts_getQueueLog (DTS *dts, char *qname, char *logname)
char * dts_getNextQueueDir (DTS *dts, char *qname)
Get the next queue directory name.
int dts_queueGetCurrent (char *fname)
Get the number of the currrently active spool.
void dts_queueSetCurrent (char *fname, int val)
Set the number of the currrently active spool.
int dts_queueGetNext (char *fname)
Get the number of the next active spool.
void dts_queueSetNext (char *fname, int val)
Set the number of the next active spool.
void dts_queueGetInitTime (dtsQueue *dtsq, int *sec, int *usec)
void dts_queueSetInitTime (dtsQueue *dtsq, struct timeval t)
void dts_queueCleanup (DTS *dts, dtsQueue *dtsq)
Clean up the spool directory before processing.
Control * dts_loadControl (char *path, Control *ctrl)
Load the control file into a struct.
int dts_saveControl (Control *ctrl, char *path)
Save the control struct.
int dts_logControl (Control *ctrl, int stat, char *path)
Make a log entry of the Control structure.
void dts_printControl (Control *ctrl, FILE *fd)
Print the control struct.
char * dts_fmtQueueCmd (dtsQueue *dtsq, Control *ctrl)
Format a queue delivery command.
char * dts_verifyDTS (char *host, char *qname, char *fname)
Verify a DTS queue connection.
int dts_queueProcess (dtsQueue *dtsq, char *lpath, char *rpath, char *fname)
Process a file to submit it to the named queue.
int dts_queueInitControl (char *qhost, char *qname, char *qpath, char *opath, char *lfname, char *fname, char *dfname)
Initialize the control structure.
void dts_queueLock (dtsQueue *dtsq)
Set the mutex lock on the queue.
void dts_queueUnlock (dtsQueue *dtsq)
Unset the mutex lock on the queue.
char * dts_queueFromPath (char *path)
Get queue name from a path.
char * dts_queueNameFmt (char *qname)
Format a queue name to 6 chars.
void dts_queueDelete (DTS *dts, char *qpath)
Delete the complete spool directory.
int dts_logXFerStats (Control *ctrl, xferStat *xfs, int stat, char *path)
Make a log entry of the transfer statistics.
int dts_queueSetStats (dtsQueue *dtsq, xferStat *xfs)
Update the transfer statistics for the queue.
queueStat * dts_queueGetStats (dtsQueue *dtsq)
Get the stats structure from a queue.
Variables
DTS * dts
int dts_monitor
Detailed Description
DTS queue utilities.
DTSQUEUEUTIL.C -- DTS queue utilities.
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
char* dts_fmtQueueCmd (dtsQueue * dtsq, Control * ctrl)
Format a queue delivery command.
DTS_FMTQUEUECMD -- Format a queue delivery command.
Parameters:
dtsq DTS queue structure
ctrl transfer control parameters
Returns: formatted command string
References dts_getDeliveryPath().
Referenced by dts_Deliver(), and dts_Ingest().
char* dts_getNextQueueDir (DTS * dts, char * qname)
Get the next queue directory name.
DTS_GETNEXTQUEUEDIR -- Get the next queue directory name.
Parameters:
dts DTS struct pointer
qname name of the queue
Returns: path to next working spool dir
References dts_queueLookup(), dts_sandboxPath(), and dtsLog().
Referenced by dts_initTransfer(), and dts_queueAccept().
char* dts_getQueuePath (DTS * dts, char * qname)
Get the path to the spool dir for a given queue.
DTS_GETQUEUEPATH -- Get queue path.
Parameters:
dts DTS struct pointer
qname name of the queue
Returns: path to queue directory
Referenced by dts_initTransfer(), and dts_queueAccept().
Control* dts_loadControl (char * path, Control * ctrl)
Load the control file into a struct.
DTS_LOADCONTROL -- Load the control file into a struct.
Parameters:
path path to control file
ctrl pointer to Control struct
Returns: loaded Control structure
References dts_fclose(), dts_fileSize(), dts_fopen(), dtsGets(), and dtsLog().
Referenced by dts_endTransfer().
int dts_logControl (Control * ctrl, int stat, char * path)
Make a log entry of the Control structure.
DTS_LOGCONTROL -- Make a log entry of the Control structure.
Parameters:
ctrl control structure
stat status flag
path path to control file
Returns: OK or ERR code
References dts_fclose(), dts_fopen(), and dts_logtime().
int dts_logXFerStats (Control * ctrl, xferStat * xfs, int stat, char * path)
Make a log entry of the transfer statistics.
DTS_LOGXFERSTATS -- Make a log entry of the transfer statistics
Parameters:
ctrl control structure
xfs transfer stats structure
stat status flag
path path to control file
Returns: OK or ERR code
References dts_fopen(), and dts_logtime().
Referenced by dts_endTransfer().
void dts_printControl (Control * ctrl, FILE * fd)
Print the control struct.
DTS_PRINTCONTROL -- Print the control struct.
Parameters:
cpath path to control file
fd file descriptor to which to write
Returns: nothing
Referenced by dts_saveControl().
void dts_queueCleanup (DTS * dts, dtsQueue * dtsq)
Clean up the spool directory before processing.
DTS_QUEUECLEANUP -- Clean up the spool directory before processing.
Parameters:
dts DTS structure
dtsq DTS queue structure
Returns: nothing
References dts_queueGetCurrent(), dts_queueGetNext(), and dtsLog().
void dts_queueDelete (DTS * dts, char * qpath)
Delete the complete spool directory.
DTS_QUEUEDELETE -- Delete the complete spool directory.
Parameters:
dts DTS struct pointer
qpath spool queue directory path
Returns: nothing
References dts_queueFromPath(), dts_unlink(), and dtsLog().
Referenced by dts_endTransfer().
char* dts_queueFromPath (char * path)
Get queue name from a path.
DTS_QUEUEFROMPATH -- Get queue name from a path.
Parameters:
path spool queue directory path
Returns: queue name
Referenced by dts_hostFrom(), dts_hostTo(), dts_queueDelete(), dts_xferPullFile(), dts_xferPushFile(), dts_xferReceiveFile(), and dts_xferSendFile().
int dts_queueGetCurrent (char * fname)
Get the number of the currrently active spool.
DTS_QUEUEGETCURRENT -- Get the number of the currrently active spool.
Parameters:
fname path to 'current' file
Returns: queue current value
References dts_fclose(), and dts_fopen().
Referenced by dts_endTransfer(), dts_flushQueue(), dts_nodeStat(), and dts_queueCleanup().
int dts_queueGetNext (char * fname)
Get the number of the next active spool.
DTS_QUEUEGETNEXT -- Get the number of the next active spool.
Parameters:
fname path to 'next' file
Returns: queue next value
References dts_fclose(), and dts_fopen().
Referenced by dts_flushQueue(), dts_nodeStat(), and dts_queueCleanup().
queueStat* dts_queueGetStats (dtsQueue * dtsq)
Get the stats structure from a queue.
DTS_QUEUEGETSTATS -- Get the stats structure from a queue.
Parameters:
dtsq DTS Queue structure
Returns: stats structure
References dts_fclose(), and dts_fopen().
Referenced by dts_nodeStat().
int dts_queueInitControl (char * qhost, char * qname, char * qpath, char * opath, char * lfname, char * fname, char * dfname)
Initialize the control structure.
DTS_QUEUEINITCONTROL -- Initialize the control structure.
Parameters:
qhost DTS Queue host name
qname queue name
qpath queue path name
opath output path name
lpath local path name
fname filename (no path)
dfname delivery filename
Returns: status
References dts_du(), dts_getAliasDest(), dts_getLocalHost(), dts_hostSetQueueControl(), dts_isDir(), dts_pathDir(), and dts_pathFname().
void dts_queueLock (dtsQueue * dtsq)
Set the mutex lock on the queue.
DTS_QUEUELOCK -- Set the mutex lock on the queue.
Parameters:
dtsq DTS queue pointer
Returns: nothing
dtsQueue* dts_queueLookup (char * qname)
Lookup a DTS queue struct by name.
DTS_QUEUELOOKUP -- Lookup a DTS queue struct by name.
Parameters:
qname name of the queue
Returns: dtsQueue struct corresponding to qname
Referenced by dts_DestDir(), dts_endTransfer(), dts_flushQueue(), dts_Get(), dts_getNextQueueDir(), dts_getQueueCmd(), dts_getQueueCount(), dts_getQueueDir(), dts_getQueueStat(), dts_initTransfer(), dts_pauseQueue(), dts_printQueueCfg(), dts_qstatDiskEnd(), dts_qstatDiskStart(), dts_qstatDlvrEnd(), dts_qstatDlvrStart(), dts_qstatDlvrStat(), dts_qstatEnd(), dts_qstatInit(), dts_qstatNetEnd(), dts_qstatNetStart(), dts_qstatNetStat(), dts_qstatSetFName(), dts_qstatSetSize(), dts_qstatStart(), dts_qstatSummary(), dts_qstatXferStat(), dts_queueRelease(), dts_queueSetControl(), dts_queueUpdateStats(), dts_setQueueCmd(), dts_setQueueCount(), dts_setQueueDir(), dts_setQueueStat(), dts_shutdownQueue(), dts_startQueue(), dts_stopQueue(), and dts_verifyDTS().
char* dts_queueNameFmt (char * qname)
Format a queue name to 6 chars.
DTS_QUEUENAMEFMT -- Format a queue name to 6 chars.
Parameters:
qname full-length queue name
Returns: shortened queue name
Referenced by dts_Deliver(), dts_endTransfer(), dts_initTransfer(), dts_qstatSummary(), dts_queueProcess(), dts_queueSetControl(), dts_xferPullFile(), dts_xferPushFile(), dts_xferReceiveFile(), and dts_xferSendFile().
int dts_queueProcess (dtsQueue * dtsq, char * lpath, char * rpath, char * fname)
Process a file to submit it to the named queue.
DTS_QPROCESS -- Process a file to submit it to the named queue.
Parameters:
dtsq DTS queue pointer
lpath local path
rpath remote path
fname filename to transfer
Returns: status result
References dts_cfgQMethodStr(), dts_cfgQModeStr(), dts_getAliasDest(), dts_getLocalIP(), dts_hostTo(), dts_hostUpStats(), dts_pathFname(), dts_queueNameFmt(), dts_resolveHost(), dts_sandboxPath(), dtsErrLog(), and dtsLog().
void dts_queueSetCurrent (char * fname, int val)
Set the number of the currrently active spool.
DTS_QUEUESETCURRENT -- Set the number of the currrently active spool.
Parameters:
fname path to 'current' file
val value to set
Returns: nothing
References dts_fclose(), and dts_fopen().
Referenced by dts_endTransfer(), dts_flushQueue(), and dts_initServerRoot().
void dts_queueSetNext (char * fname, int val)
Set the number of the next active spool.
DTS_QUEUESETNEXT -- Set the number of the next active spool.
Parameters:
fname path to 'Next' file
val value to set
Returns: nothing
References dts_fclose(), and dts_fopen().
int dts_queueSetStats (dtsQueue * dtsq, xferStat * xfs)
Update the transfer statistics for the queue.
DTS_QUEUESETSTATS -- Update the transfer statistics for the queue.
Parameters:
dtsq DTS Queue struct pointer
xfs transfer statistics struct
Returns: nothing
References dts_fclose(), and dts_fopen().
Referenced by dts_queueUpdateStats().
void dts_queueUnlock (dtsQueue * dtsq)
Unset the mutex lock on the queue.
DTS_QUEUEUNLOCK -- Unset the mutex lock on the queue.
Parameters:
dtsq DTS queue pointer
Returns: nothing
int dts_saveControl (Control * ctrl, char * path)
Save the control struct.
DTS_SAVECONTROL -- Save the control struct.
Parameters:
ctrl control structure
cpath path to control file
Returns: OK or ERR code
References dts_fclose(), dts_fopen(), and dts_printControl().
Referenced by dts_Ingest().
char* dts_verifyDTS (char * host, char * qname, char * fname)
Verify a DTS queue connection.
DTS_VERIFYDTS -- Verify a DTS queue connection.
Parameters:
host DTS host name
qname queue name
fname file name to transfer
Returns: remote path to queue directory (caller frees ptr)
References dts_hostContact(), dts_hostInitTransfer(), dts_hostPing(), dts_queueLookup(), and dtsLog().