dtsQueue.c File Reference
DTS queue methods.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include <ctype.h>
#include <stdarg.h>
#include `dts.h`
Defines
#define DEBUG (dts&&dts $\rightarrow$ debug>2)
Functions
int dts_hostInitTransfer (char *host, char *qname, char *fname, char *msg)
See if a queue will accept a new entry.
int dts_hostEndTransfer (char *host, char *qname, char *qpath)
Terminate the file transfer.
int dts_hostQueueAccept (char *host, char *qname, char *fname, char *msg)
See if a queue will accept a new entry.
int dts_hostQueueComplete (char *host, char *qname, char *qpath)
Complete a file transfer.
int dts_hostQueueRelease (char *host, char *qname)
Release the lock semaphore on a queue.
int dts_hostQueueValid (char *host, char *qname)
See if a queue name is valid on the host.
int dts_hostSetQueueControl (char *host, char *qPath, Control *ctrl)
Set the control params for the transfer.
Variables
DTS * dts
int dts_monitor
int queue_delay
Detailed Description
DTS queue methods.
DTSQUEUE.C -- DTS queue methods.
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
int dts_hostEndTransfer (char * host, char * qname, char * qpath)
Terminate the file transfer.
DTS_HOSTENDTRANSFER -- Terminate the file transfer.
Parameters:
host host machine name (or IP string)
qname name of queue
qpath path to queue directory
Returns: OK or ERR
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostInitTransfer (char * host, char * qname, char * fname, char * msg)
See if a queue will accept a new entry.
DTS_HOSTINITTRANSFER -- See if a queue will accept a new entry.
Parameters:
host host machine name (or IP string)
qname name of queue
fname name of queue
msg returned message/path
Returns: OK or ERR
References dts_closeClient(), dts_cmdInit(), dts_du(), dts_getClient(), and dtsLog().
Referenced by dts_verifyDTS().
int dts_hostQueueAccept (char * host, char * qname, char * fname, char * msg)
See if a queue will accept a new entry.
DTS_HOSTQUEUEACCEPT -- See if a queue will accept a new entry.
Parameters:
host host machine name (or IP string)
qname name of queue
fname name of queue
msg returned message/path
Returns: OK or ERR
References dts_closeClient(), dts_cmdInit(), dts_du(), and dts_getClient().
int dts_hostQueueComplete (char * host, char * qname, char * qpath)
Complete a file transfer.
DTS_HOSTQUEUECOMPLETE -- Complete a file transfer.
Parameters:
host host machine name (or IP string)
qname name of queue
qpath path to queue directory
Returns: OK or ERR
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostQueueRelease (char * host, char * qname)
Release the lock semaphore on a queue.
DTS_HOSTQUEUERELEASE -- Release the lock semaphore on a queue.
Parameters:
host host machine name (or IP string)
qname name of queue
Returns: OK or ERR
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostQueueValid (char * host, char * qname)
See if a queue name is valid on the host.
DTS_HOSTQUEUEVALID -- See if a queue name is valid on the host.
Parameters:
host host machine name (or IP string)
qname name of queue
Returns: OK or ERR
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
int dts_hostSetQueueControl (char * host, char * qPath, Control * ctrl)
Set the control params for the transfer.
DTS_HOSTSETQUEUECONTROL -- Set the control params for the transfer.
Parameters:
host host machine name (or IP string)
qPath path to queue directory being used
ctrl Control data struct
Returns: OK or ERR
References dts_closeClient(), dts_cmdInit(), and dts_getClient().
Referenced by dts_queueInitControl().