dtsQueueStat.c File Reference
DTS queue statistics utilities.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include <pthread.h>
#include <fcntl.h>
#include <ctype.h>
#include <stdarg.h>
#include `dtsPSock.h`
#include `dts.h`
Defines
#define DEBUG (dts&&dts $\rightarrow$ debug)
#define QSTAT dtsq $\rightarrow$ qstat
Functions
void dts_qstatInit (char *qname, char *fname, size_t size)
Initialize the transfer stat struct.
void dts_qstatSetFName (char *qname, char *fname)
Set the file name being transferred in a queue.
void dts_qstatSetSize (char *qname, size_t size)
Set the fize of file being transferred in a queue.
void dts_qstatStart (char *qname)
Set the start time of file being transferred in a queue.
void dts_qstatEnd (char *qname)
Set the end time of file being transferred in a queue.
void dts_qstatNetStart (char *qname)
Set the start time of network transfer time.
void dts_qstatNetEnd (char *qname)
Set the end time of network transfer time.
void dts_qstatDiskStart (char *qname)
Set the start time of network transfer time.
void dts_qstatDiskEnd (char *qname)
Set the end time of network transfer time.
void dts_qstatDlvrStart (char *qname)
Set the start time of network transfer time.
void dts_qstatDlvrEnd (char *qname)
Set the end time of network transfer time.
void dts_qstatXferStat (char *qname, int stat)
Set the transfer status code.
void dts_qstatNetStat (char *qname, int stat)
Set the network transfer status code.
void dts_qstatDlvrStat (char *qname, int stat)
Set the delivery status code.
void dts_qstatSummary (DTS *dts, char *qname)
Print the transfer summary to the log.
void dts_qstatPrint (char *qname)
Variables
DTS * dts
int dts_monitor
Detailed Description
DTS queue statistics utilities.
DTSQUEUESTAT.C -- DTS queue statistics utilities.
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
void dts_qstatDiskEnd (char * qname)
Set the end time of network transfer time.
DTS_QSTATDISKEND -- Set the end time of network transfer time
Parameters:
qname name of the queue
References dts_queueLookup().
Referenced by dts_endTransfer().
void dts_qstatDiskStart (char * qname)
Set the start time of network transfer time.
DTS_QSTATDISKSTART -- Set the start time of network transfer time
Parameters:
qname name of the queue
References dts_queueLookup().
Referenced by dts_endTransfer().
void dts_qstatDlvrEnd (char * qname)
Set the end time of network transfer time.
DTS_QSTATDISKEND -- Set the end time of network transfer time
Parameters:
qname name of the queue
References dts_queueLookup().
Referenced by dts_Deliver(), and dts_Ingest().
void dts_qstatDlvrStart (char * qname)
Set the start time of network transfer time.
DTS_QSTATDISKSTART -- Set the start time of network transfer time
Parameters:
qname name of the queue
References dts_queueLookup().
Referenced by dts_Deliver(), and dts_Ingest().
void dts_qstatDlvrStat (char * qname, int stat)
Set the delivery status code.
DTS_QSTATDLVRSTAT -- Set the delivery status code.
Parameters:
qname name of the queue
stat OK or ERR
References dts_queueLookup().
Referenced by dts_Deliver(), dts_endTransfer(), and dts_Ingest().
void dts_qstatEnd (char * qname)
Set the end time of file being transferred in a queue.
DTS_QSTATEND -- Set the end time of file being transferred in a queue.
Parameters:
qname name of the queue
References dts_queueLookup().
Referenced by dts_endTransfer().
void dts_qstatInit (char * qname, char * fname, size_t size)
Initialize the transfer stat struct.
DTS_QSTATINIT -- Initialize the transfer stat struct.
Parameters:
fname name of the file
qname name of the queue
size size of the file
References dts_queueLookup().
Referenced by dts_initTransfer().
void dts_qstatNetEnd (char * qname)
Set the end time of network transfer time.
DTS_QSTATNETEND -- Set the end time of network transfer time
Parameters:
qname name of the queue
References dts_queueLookup().
Referenced by dts_xferPullFile(), and dts_xferReceiveFile().
void dts_qstatNetStart (char * qname)
Set the start time of network transfer time.
DTS_QSTATNETSTART -- Set the start time of network transfer time
Parameters:
qname name of the queue
References dts_queueLookup().
Referenced by dts_xferPullFile(), and dts_xferReceiveFile().
void dts_qstatNetStat (char * qname, int stat)
Set the network transfer status code.
DTS_QSTATNETSTAT -- Set the network transfer status code.
Parameters:
qname name of the queue
stat OK or ERR
References dts_queueLookup().
void dts_qstatSetFName (char * qname, char * fname)
Set the file name being transferred in a queue.
DTS_QSTATSETFNAME -- Set the file name being transferred in a queue.
Parameters:
qname queue name
fname file name
References dts_queueLookup().
Referenced by dts_endTransfer().
void dts_qstatSetSize (char * qname, size_t size)
Set the fize of file being transferred in a queue.
DTS_QSTATSETSIZE -- Set the fize of file being transferred in a queue.
Parameters:
qname queue name
size size of the file
References dts_queueLookup().
void dts_qstatStart (char * qname)
Set the start time of file being transferred in a queue.
DTS_QSTATSTART -- Set the start time of file being transferred in a queue.
Parameters:
qname name of the queue
References dts_queueLookup().
Referenced by dts_initTransfer().
void dts_qstatSummary (DTS * dts, char * qname)
Print the transfer summary to the log.
DTS_QSTATSUMMARY -- Print the transfer summary to the log.
Parameters:
dts DTS struct pointer
qname name of the queue
References dts_queueLookup(), dts_queueNameFmt(), and dtsLog().
Referenced by dts_endTransfer().
void dts_qstatXferStat (char * qname, int stat)
Set the transfer status code.
DTS_QSTATXFERSTAT -- Set the transfer status code.
Parameters:
qname name of the queue
stat OK or ERR
References dts_queueLookup().