dtsSandbox.c File Reference
DTS file system sandbox routines.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
#include `dts.h`
Defines
#define DEBUG 0
#define MAX_DEPTH 64
Functions
char * dts_sandboxPath (char *in)
Return the sandboxed path name.
Variables
DTS * dts
int dts_monitor
Detailed Description
DTS file system sandbox routines.
DTSSANDBOX.C -- DTS file system sandbox routines.
Author: Mike Fitzpatrick, NOAO
Date: 6/15/09
Define Documentation
#define MAX_DEPTH 64
DTS_PATHFIXUP -- Fix an incoming path with `..` elements so we can't use those to escape the root directory.
Function Documentation
char* dts_sandboxPath (char * in)
Return the sandboxed path name.
DTS_SANDBOXPATH -- Return the sandboxed path name.
Parameters:
path input path name (not chrooted)
Returns: sandboxed path (caller must free ptr)
References dts_getLocalRoot(), dts_isDir(), dts_isLink(), and dts_readLink().
Referenced by dts_Access(), dts_addControlHistory(), dts_Cat(), dts_CheckDir(), dts_Checksum(), dts_Chmod(), dts_Copy(), dts_Delete(), dts_Dir(), dts_DiskFree(), dts_DiskUsed(), dts_endTransfer(), dts_FMode(), dts_FSize(), dts_FTime(), dts_getNextQueueDir(), dts_Mkdir(), dts_nodeStat(), dts_Prealloc(), dts_queueComplete(), dts_queueProcess(), dts_queueSetControl(), dts_Read(), dts_Rename(), dts_SetRoot(), dts_Stat(), dts_Touch(), psReceiveFile(), psSendFile(), udtReceiveFile(), and udtSendFile().