dtsSockUtil.c File Reference
DTS socket utilities.
#include <pthread.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <netdb.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/select.h>
#include <fcntl.h>
#include <sys/errno.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include `dts.h`
#include `dtsUDT.h`
#include `dtsPSock.h`
#include `udtc.h`
Defines
#define DEBUG 0
Functions
void dts_setNonBlock (int sock)
void dts_setBlock (int sock)
int dts_openServerSocket (int port)
Open a socket to be used on the 'server' side.
int dts_testServerSocket (int port)
Test whether a server socket is in use.
int dts_getOpenPort (int port, int maxTries)
Get an open server port.
int dts_openClientSocket (char *host, int port, int retry)
Open a socket to be used on the 'client' side.
int dts_openUDTServerSocket (int port, int rate)
int dts_openUDTClientSocket (char *host, int port, int retry)
Open a socket to be used on the 'client' side.
int dts_sockRead (int fd, void *vptr, int nbytes)
Recv exactly `n` bytes from a socket descriptor.
int dts_sockWrite (int fd, void *vptr, int nbytes)
Send exactly `n` bytes to a socket descriptor.
int dts_udtRead (int fd, void *vptr, long nbytes, int flags)
Recv exactly `n` bytes from a UDT socket descriptor.
int dts_udtWrite (int fd, void *vptr, long nbytes, int flags)
Send exactly `n` bytes to a UDT socket descriptor.
Variables
pthread_mutex_t cs_mut = PTHREAD_MUTEX_INITIALIZER
pthread_mutex_t ss_mut = PTHREAD_MUTEX_INITIALIZER
Detailed Description
DTS socket utilities.
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
int dts_getOpenPort (int port, int maxTries)
Get an open server port.
dts_getOpenPort -- Get an open server port. The input port is a high value, if not immediately open we decrement the port up to the max number of attempts.
Parameters:
port initial port number to open (high value)
maxTries max ports to test
Returns: open port number
References dts_testServerSocket().
int dts_openClientSocket (char * host, int port, int retry)
Open a socket to be used on the 'client' side.
dts_openClientSocket -- Open a socket to be used on the 'client' side.
Parameters:
host host name
port port number to open
retry attempt to reconnect?
Returns: socket descriptor
References dts_getHostByName(), and dts_getLocalIP().
Referenced by dts_hostContact(), psReceiveFile(), and psSendFile().
int dts_openServerSocket (int port)
Open a socket to be used on the 'server' side.
dts_openServerSocket -- Open a socket to be used on the 'server' side.
Parameters:
port port number to open
Returns: socket descriptor
References dts_getLocalIP(), and dtsErrLog().
Referenced by psReceiveFile(), and psSendFile().
int dts_openUDTClientSocket (char * host, int port, int retry)
Open a socket to be used on the 'client' side.
dts_openUDTClientSocket -- Open a socket to be used on the 'client' side.
Parameters:
host host name
port port number to open
retry attempt to reconnect?
Returns: socket descriptor
References dts_getHostByName(), and dts_getLocalIP().
Referenced by udtReceiveFile(), and udtSendFile().
void dts_setBlock (int sock)
DTS_SETBLOCK -- Set a blocking mode on the descriptor.
void dts_setNonBlock (int sock)
DTS_SETNONBLOCK -- Set a non-blocking mode on the descriptor.
Referenced by dts_fileWrite(), dts_sockRead(), dts_sockWrite(), and dts_udtWrite().
int dts_sockRead (int fd, void * vptr, int nbytes)
Recv exactly `n` bytes from a socket descriptor.
DTS_SOCKREAD -- Read exactly `n` bytes from a socket descriptor.
Parameters:
fd file descriptor
vptr data buffer to be written
nbytes number of bytes to write
Returns: number of bytes written
References dts_setNonBlock(), dtsErrLog(), and psock_checksum_policy.
Referenced by psReceiveStripe(), and psSendStripe().
int dts_sockWrite (int fd, void * vptr, int nbytes)
Send exactly `n` bytes to a socket descriptor.
DTS_SOCKWRITE -- Write exactly `n` bytes to a socket descriptor.
Parameters:
fd file descriptor
vptr data buffer to be written
nbytes number of bytes to write
Returns: number of bytes written
References dts_setNonBlock(), dtsErrLog(), and psock_checksum_policy.
Referenced by psReceiveStripe(), and psSendStripe().
int dts_testServerSocket (int port)
Test whether a server socket is in use.
dts_testServerSocket -- Test whether a server socket is in use.
Parameters:
port port number to open
Returns: status (0=free, 1=in-use)
Referenced by dts_getOpenPort().
int dts_udtRead (int fd, void * vptr, long nbytes, int flags)
Recv exactly `n` bytes from a UDT socket descriptor.
DTS_UDTREAD -- Read exactly `n` bytes from a UDT socket descriptor.
Parameters:
fd file descriptor
vptr data buffer to be written
nbytes number of bytes to write
flags option flags
Returns: number of bytes written
References dtsErrLog(), and udt_checksum_policy.
Referenced by udtReceiveStripe().
int dts_udtWrite (int fd, void * vptr, long nbytes, int flags)
Send exactly `n` bytes to a UDT socket descriptor.
DTS_UDTWRITE -- Write exactly `n` bytes to a UDT socket descriptor.
Parameters:
fd file descriptor
vptr data buffer to be written
nbytes number of bytes to write
flags option flags
Returns: number of bytes written
References dts_setNonBlock(), dtsErrLog(), and udt_checksum_policy.
Referenced by udtSendStripe().