dtsSem.c File Reference
DTS utilities to manage semaphores easily.
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <semaphore.h>
#include <errno.h>
#include <pthread.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include `dts.h`
Data Structures
union semun
Defines
#define SEM_STAT 18
#define SEM_INFO 19
#define IPC_INFO 3
#define USE_SEMOP 1
Functions
int dts_semInit (int id, int initVal)
int dts_semRemove (int id)
int dts_semSetVal (int id, int val)
int dts_semGetVal (int id)
int dts_semDecr (int id)
int dts_semIncr (int id)
void dts_semInitId (int id)
Variables
DTS * dts
Detailed Description
DTS utilities to manage semaphores easily.
DTSSEM.C -- DTS utilities to manage semaphores easily.
Author: Mike Fitzpatrick, NOAO
Date: 6/10/09
Function Documentation
int dts_semDecr (int id)
Decrement the semaphore value.
References dts_semGetVal().
Referenced by psReceiveFile(), psSendFile(), udtReceiveFile(), and udtSendFile().
int dts_semGetVal (int id)
Get the value.
Referenced by dts_getQueueCount(), dts_getQueueStat(), dts_initTransfer(), dts_nodeStat(), dts_pauseQueue(), dts_semDecr(), dts_shutdownQueue(), dts_startQueue(), dts_xferPullFile(), and dts_xferPushFile().
int dts_semIncr (int id)
Increment the semaphore value.
Referenced by dts_endTransfer().
int dts_semInit (int id, int initVal)
Create and/or initialize the semaphore.
References dts_semSetVal().
Referenced by dts_xferPullFile(), and dts_xferPushFile().
void dts_semInitId (int id)
Initialize the semaphore interface starting ID.
Referenced by dts_loadConfigFile().
int dts_semRemove (int id)
Destroy the semaphore.
Referenced by dts_xferPullFile(), and dts_xferPushFile().
int dts_semSetVal (int id, int val)
Set the value.
Referenced by dts_Deliver(), dts_Ingest(), dts_pauseQueue(), dts_queueRelease(), dts_semInit(), dts_setQueueCount(), dts_setQueueStat(), dts_shutdownQueue(), dts_startQueue(), and dts_stopQueue().