dtsUDT.c File Reference
DTS UDT transfer routines.
#include <pthread.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <netdb.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <fcntl.h>
#include <sys/errno.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include `dts.h`
#include `dtsUDT.h`
#include `dtsPSock.h`
#include `udtc.h`
Defines
#define _PTCP_SRC_
#define UDT_DEBUG 0
#define USE_PTHREAD_JOIN
Functions
int udtSpawnThreads (void *worker, int nthreads, char *dir, char *fname, long fsize, int mode, int rate, int port, char *host, int verbose, pthread_t *tids)
Spawn a worker thread for the transfer.
int * udtCollectThreads (int nthreads, pthread_t *tids)
Collect worker threads for the transfer.
void udtSendFile (void *data)
Send a file to a remote DTS.
void udtReceiveFile (void *data)
Read a file from a remote DTS.
int udtSendStripe (int sock, unsigned char *dbuf, long offset, int tnum, long maxbytes)
Do actual transfer of data stripe to the socket.
unsigned char * udtReceiveStripe (int sock, long offset, int tnum)
Read data stripe from the socket connection.
void udtComputeStripe (long fsize, int nthreads, int tnum, long *chsize, long *start, long *end)
Variables
pthread_mutex_t udt_mutex = PTHREAD_MUTEX_INITIALIZER
int udt_checksum_policy = CS_NONE
struct timeval io_tv
int queue_delay
int thread_sem
DTS * dts
int first_write
Detailed Description
DTS UDT transfer routines.
DTSUDT.C -- DTS UDT transfer routines.
Author: Mike Fitzpatrick, Travis Semple, NOAO
Date: 3/10/13
Function Documentation
int udtCollectThreads (int nthreads, pthread_t * tids)
Collect worker threads for the transfer.
UDTCOLLECTTHREADS -- Collect the worker threads for the transfer. Our onl job here is start a thread to rejoin the previously createed threads.
Parameters:
nthreads number of threads to create
tids thread IDs
Returns: status code
udtReceiveFile (void * data)
Read a file from a remote DTS.
UDTRECEIVEFILE -- Receive a file from a remote DTS.
This function can be called to read a portion of a file from a remote host. Arguments are passed in through a generic 'data' pointer to the psArg struct defined for this 'stripe' of the data.
In this procedure, we act as a client in the connection, i.e. the transfer won't begin until we connect to a remote server sending the data.
Parameters:
data caller thread data
Returns: nothing
References dts_fileOpen(), dts_fileWrite(), dts_makePath(), dts_openUDTClientSocket(), dts_preAlloc(), dts_sandboxPath(), dts_semDecr(), dtsErrLog(), dtsLog(), dtsTimeLog(), udt_mutex, and udtReceiveStripe().
Referenced by dts_xferPullFile(), and dts_xferReceiveFile().
uchar * udtReceiveStripe (int sock, long offset, int tnum)
Read data stripe from the socket connection.
UDTRECEIVESTRIPE -- Do the actual transfer of the data stripe to the client connection. A 'stripe' of data is actually transferred in much smaller 'chunks' which can be tuned to be optimal for the given connection. The checksum policy allows us to perform a checksum of the data either for the entire stripe, or for each individual chunk. The former is generally more efficient as it involves fewer round-trips to the client (i.e. send the checksum and wait for verification before sending next chunk). File-level checksum policy is enforced by our parent.
Parameters:
sock socket descriptor
offset file offset for this stripe
tnum thread (i.e. stripe) number
Returns: a pointer to the data read
References dts_debugLevel(), dts_udtRead(), and dtsLog().
Referenced by udtReceiveFile().
udtSendFile (void * data)
Send a file to a remote DTS.
UDTSENDFILE -- Send a file to a remote DTS using UDT.
This function can be called to send a portion of a file to a remote host. Arguments are passed in through a generic 'data' pointer to the psArg struct defined for this 'stripe' of the data.
In this procedure, we act as a server, i.e. we open the specified tcp/ip socket and wait for a client connection before beginning any transfer.
Parameters:
data caller thread data
Returns: nothing
References dts_fileClose(), dts_fileOpen(), dts_fileRead(), dts_makePath(), dts_openUDTClientSocket(), dts_sandboxPath(), dts_semDecr(), dtsErrLog(), dtsLog(), dtsTimeLog(), udt_mutex, and udtSendStripe().
Referenced by dts_xferPushFile(), and dts_xferSendFile().
int udtSendStripe (int sock, unsigned char * dbuf, long offset, int tnum, long maxbytes)
Do actual transfer of data stripe to the socket.
UDTSENDSTRIPE -- Do the actual transfer of the data stripe to the client connection. A 'stripe' of data is actually transferred in much smaller 'chunks' which can be tuned to be optimal for the given connection. The checksum policy allows us to perform a checksum of the data either for the entire stripe, or for each individual chunk. The former is generally more efficient as it involves fewer round-trips to the client (i.e. send the checksum and wait for verification before sending next chunk). File-level checksum policy is enforced by our parent.
Parameters:
sock socket descriptor
dbuf data buffer
offset file offset for this stripe
tnum thread number
maxbytes max bytes to transfer
Returns: number of chunks sent
References dts_debugLevel(), dts_udtWrite(), dtsErrLog(), and dtsTimeLog().
Referenced by udtSendFile().
int udtSpawnThreads (void * worker, int nthreads, char * dir, char * fname, long fsize, int mode, int rate, int port, char * host, int verbose, pthread_t * tids)
Spawn a worker thread for the transfer.
UDTSPAWNTHREADS -- Spawn a worker thread for the transfer. All we do here is start a thread to run the function passed in. This may be used to either read or write the data.
Parameters:
worker worker function
nthreads number of threads to create
dir working directory
fname file name
fsize file size
mode transfer mode (push or pull)
rate transfer rate (Mbps)
port client base port number
host client host name
verbose verbose output flag
tids thread id array
Returns: status code
References dtsErrLog(), and psComputeStripe().
Referenced by dts_xferPullFile(), dts_xferPushFile(), dts_xferReceiveFile(), and dts_xferSendFile().
Variable Documentation
int udt_checksum_policy = CS_NONE
FIXME -- CS_STRIPE and CS_PACKET not working......
Referenced by dts_udtRead(), and dts_udtWrite().
pthread_mutex_t udt_mutex = PTHREAD_MUTEX_INITIALIZER
Mutex lock for thread startup to protect file I/O.
Referenced by udtReceiveFile(), and udtSendFile().