dtsUtil.c File Reference
DTS Checksum utility methods.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <ctype.h>
#include <netdb.h>
#include <pthread.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <signal.h>
#include <fcntl.h>
#include `dts.h`
Data Structures
struct hostTab
struct hostent_wrapper
Defines
#define USE_DNS_IP
#define NUM_STR_BUF 1024
#define SZ_BUF_STR 1024
#define STRBUF_MAX_WAIT 5
#define _DTS_SRC_ 1
Typedefs
typedef struct hostTab * hostTabP
Functions
void dtsDaemonize (DTS *dts)
void dts_sigHandler (int sig)
void dts_setQueueShutdown (int level)
void dts_pause ()
void dtsShm (DTS *dts)
char * dts_localTime ()
char * dts_UTTime ()
void dts_getPrimaryIP (char *buffer, size_t buflen)
char * dts_getLocalIP ()
char * dts_getLocalHost ()
struct hostent * dts_getHostByName (char *name)
void dts_printHostTable ()
struct hostent * dts_dupHostent (struct hostent *hentry)
char * dts_getAliasHost (char *alias)
int dts_getAliasPort (char *alias)
char * dts_getAliasDest (char *alias)
char * dts_resolveHost (char *hostname)
char * dts_logtime ()
void dts_tstart (struct timeval *tv)
double dts_tstop (struct timeval tv1)
double dts_timediff (struct timeval t1, struct timeval t2)
void measure_start (void)
Timer utils.
void measure_stop (long transferred)
Stop timer and print summary of transfer stats.
double transferMb (long fileSize, int sec, int usec)
Return throughput in megabits/s.
double transferMB (long fileSize, int sec, int usec)
Return throughput in megabytes/s.
char * dts_fmtMode (char *lp, int flags)
int dts_patMatch (char *str, char *pattern)
int dts_isTemplate (char *s)
char * dtsGets (char *s, int len, FILE *fp)
char * dts_strbuf (char *s)
void dtsError (char *msg)
int dts_debugLevel ()
char * dts_printDTS (DTS *dts, FILE *fd)
char * dts_printDTSClient (DTS *dts, FILE *fd)
char * dts_printAllQueues (DTS *dts, FILE *fd)
char * dts_printQueue (dtsQueue *dtsq, FILE *fd)
void doprnt (char *buf, char *format,...)
int dtsSleep (unsigned int seconds)
int base64_encode (unsigned char *source, size_t sourcelen, char *target, size_t targetlen)
int base64_decode (char *source, unsigned char *target, size_t targetlen)
Variables
DTS * dts
struct timeval measure_start_tv
struct timeval io_tv = {0, 0}
pthread_mutex_t str_mut = PTHREAD_MUTEX_INITIALIZER
const char * b64_chars
Detailed Description
DTS Checksum utility methods.
DTS Utility methods.
DTSCHECKSUM.C -- Checksum utility routines for the DTS.
md5 = dts_fileMD5 (char *fname) crc = dts_fileCRC32 (char *fname) sum = dts_fileChecksum (char *fname, int do_sysv) sum = dts_fileCRCChecksum (char *fname, unsigned int *crc)
valid = dts_fileValidate (char *fname, uint sum32, uint crc, char *md5)
checksum (uchar *data, int length, ushort *sum16, uint *sum32) sum = addcheck32 (uchar *array, int length)
Author: Mike Fitzpatrick, NOAO
Date: 6/15/09
DTSUTIL.C -- Utility routines for the DTS.
dtsDaemonize (DTS *dts) dts_sigHandler (int sig) dts_pause() dts_getLocalIP () dts_getLocalHost () dts_resolveHost (char *hostname) dts_fmtMode (char *lp, int flags) dts_patMatch (char *str, char *pattern) dts_isTemplate (char *s) dts_strbuf (char *s);
dtsGets (char *s, int len, FILE *fp) dtsError (char *msg) dts_debugLevel () dts_printDTS (DTS *dts, FILE *fd) dts_printDTSClient (DTS *dts, FILE *fd) dts_printAllQueues (DTS *dts, FILE *fd) dts_printQueue (dtsQueue *dtsq, FILE *fd)
measure_start (void) measure_stop (long transferred)
base64_encode (uchar *source, size_t sourcelen, char *target, size_t targetlen) base64_decode (char *source, unsigned char *target, size_t targetlen)
Author: Mike Fitzpatrick, NOAO
Date: 6/15/09
Define Documentation
#define _DTS_SRC_ 1
DTSERROR -- Print a fatal error message.
#define NUM_STR_BUF 1024
DTS_STRBUF -- Return a string from a static buffer.
Function Documentation
int base64_decode (char * source, unsigned char * target, size_t targetlen)
decode base64 encoded data
Parameters:
source the encoded data (zero terminated)
target pointer to the target buffer
targetlen length of the target buffer
Returns: length of converted data on success, -1 otherwise
Referenced by dts_hostCat(), dts_hostFGet(), and dts_hostRead().
int base64_encode (unsigned char * source, size_t sourcelen, char * target, size_t targetlen)
encode an array of bytes using Base64 (RFC 3548)
Parameters:
source the source buffer
sourcelen the length of the source buffer
target the target buffer
targetlen the length of the target buffer
Returns: 1 on success, 0 otherwise
Referenced by dts_Cat(), and dts_Read().
int dts_debugLevel (void)
DTS_DEBUGLEVEL -- Return the current debug level to procedures without a DTS pointer.
Referenced by psReceiveStripe(), psSendStripe(), udtReceiveStripe(), and udtSendStripe().
struct hostent* dts_dupHostent (struct hostent * hentry) [read]
DTS_DUPHOSTENT -- Duplicate a hostent structure via a deep copy.
Referenced by dts_getHostByName().
char* dts_fmtMode (char * lp, int flags)
DTS_FMTMODE -- Format the file mode permissions as a string.
Referenced by dts_Dir(), and dts_localDir().
char* dts_getAliasDest (char * alias)
DTS_GETALIASDEST -- Get the destination associated with a node alias.
Parameters:
alias client alias
Returns: destination as 'node:port'
Referenced by dts_queueInitControl(), and dts_queueProcess().
char* dts_getAliasHost (char * alias)
DTS_GETALIASHOST -- Get the host associated with a node alias.
Parameters:
alias client alias
Returns: name of host
int dts_getAliasPort (char * alias)
DTS_GETALIASPORT -- Get the port associated with a node alias.
Parameters:
alias client alias
Returns: name of host
struct hostent* dts_getHostByName (char * name) [read]
DTS_GETHOSTBYNAME -- Get the host entry associated with a (cached) name.
Parameters:
name host name
Returns: host entry structure pointer
References dts_dupHostent(), and dtsErrLog().
Referenced by dts_getLocalIP(), dts_openClientSocket(), dts_openUDTClientSocket(), and dts_resolveHost().
char* dts_getLocalHost (void)
DTS_GETLOCALHOST -- Get the local host name as a string.
Returns: name of host
Referenced by dts_hostPingSleep(), dts_loadDefaultConfig(), dts_newQueue(), and dts_queueInitControl().
char* dts_getLocalIP ()
DTS_GETLOCALIP -- Get the local IP address as a string.
Returns: character string of IP, e.g. `127.0.0.1`
References dts_getHostByName(), and dts_resolveHost().
Referenced by dts_hostFrom(), dts_hostTo(), dts_initCopyMode(), dts_isLocal(), dts_loadConfigFile(), dts_openClientSocket(), dts_openServerSocket(), dts_openUDTClientSocket(), dts_queueProcess(), dts_resolveHost(), dts_xferParsePaths(), and dts_xferPushFile().
int dts_isTemplate (char * s)
DTS_ISTEMPLATE -- Is a string a pattern template?
Referenced by dts_Delete(), dts_Dir(), dts_localDelete(), and dts_localDir().
char* dts_localTime ()
DTS_LOCALTIME - Generate a local time string.
Referenced by dts_addControlHistory().
char* dts_logtime (void)
LOGTIME - Generate a time string for the log.
Returns: a standard logfile timestring
Referenced by dts_logControl(), and dts_logXFerStats().
int dts_patMatch (char * str, char * pattern)
DTS_PATMATCH -- Match a string against a pattern template.
Referenced by dts_Dir(), dts_dirSize(), dts_localDir(), and dts_unlink().
void dts_pause (void)
DTS_PAUSE -- Dummy procedure to provide a debugger breakpoint.
void dts_printHostTable (void)
DTS_PRINTHOSTTAB -- Debug util to print host table.
char* dts_resolveHost (char * hostname)
DTS_RESOLVEHOST -- Resolve a host name to an IP string.
Parameters:
hostname FQDN hostname
Returns: character string of IP, e.g. `127.0.0.1`
References dts_cfgNameToIP(), dts_getHostByName(), dts_getLocalIP(), and dts_nameToHost().
Referenced by dts_getLocalIP(), dts_hostCwd(), dts_hostFrom(), dts_loadConfigFile(), dts_loadDefaultConfig(), dts_nameToIP(), dts_queueProcess(), and dts_xferParsePaths().
void dts_sigHandler (int sig)
DTS_SIGHANDLER -- Signal handler for the DTS daemon.
Parameters:
sig signal number
References dtsLog().
Referenced by dtsDaemonize().
char* dts_UTTime ()
DTS_UTTIME - Generate a Greenwich Mean time string.
void dtsDaemonize (DTS * dts)
DTSDAEMONIZE -- Daemonize the DTS.
Parameters:
dts DTS struct pointer
Returns:
References dts_connectToMonitor(), dts_sigHandler(), and dtsLog().
char* dtsGets (char * s, int len, FILE * fp)
DTSGETS A smart fgets() function
Read the line; unlike fgets(), we read the entire line but dump characters that go past the end of the buffer. We accept CR, LF, or CR LF for the line endings to be `safe`.
Parameters:
s string buffer
len length of buffer
fp file descriptor
Returns: pointer to next string on the stream
Referenced by dts_loadConfigFile(), dts_loadControl(), dts_loadDeliveryParams(), and dts_queueComplete().
void measure_start (void)
Timer utils.
Start timer.
References measure_start_tv.
void measure_stop (long transferred)
Stop timer and print summary of transfer stats.
Parameters:
transferred number of bytes transferred
References measure_start_tv.
double transferMB (long fileSize, int sec, int usec)
Return throughput in megabytes/s.
Parameters:
fileSize number of bytes transferred
sec transfer time seconds
usec transfer time micro-seconds
Referenced by dts_endTransfer(), dts_hostFGet(), dts_xferFile(), dts_xferPullFile(), dts_xferPushFile(), dts_xferReceiveFile(), and dts_xferSendFile().
double transferMb (long fileSize, int sec, int usec)
Return throughput in megabits/s.
Parameters:
fileSize number of bytes transferred
sec transfer time seconds
usec transfer time micro-seconds
Referenced by dts_endTransfer(), dts_xferFile(), dts_xferPullFile(), dts_xferPushFile(), dts_xferReceiveFile(), and dts_xferSendFile().
Variable Documentation
const char* b64_chars
Initial value:
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
Characters used for Base64 encoding
struct timeval measure_start_tv
Transfer and measurement utilities.
Referenced by measure_start(), and measure_stop().