dtsXfer.c File Reference
Client-callable DTS commands to transfer files TO a remote host machine..
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <dirent.h>
#include <fcntl.h>
#include `dts.h`
#include `dtsPSock.h`
Functions
int dts_hostTo (char *host, int port, int method, int rate, int loPort, int hiPort, int threads, int mode, int argc, char *argv[], xferStat *xfs)
Push a file to a remote host.
int dts_hostFrom (char *host, int port, int method, int rate, int loPort, int hiPort, int threads, int mode, int argc, char *argv[], xferStat *xfs)
Pull a file from a remote host.
int dts_xferDirTo (char *host, char *func, int method, int rate, char *path, char *root, char *prefix, xferStat *xs)
Recursively transfer a directory between hosts.
int dts_xferDirFrom (char *srcHost, char *dstHost, int dstLocal, char *func, int method, int rate, char *path, char *root, char *prefix, xferStat *xs)
Recursively transfer a directory between hosts.
int dts_xferFile (char *host, char *func, int method, int rate, char *path, int fsize, mode_t fmode, xferStat *xs)
Transfer a single file between hosts.
int dts_xferParseArgs (int argc, char *argv[], int *nthreads, int *port, int *verbose, char **path_A, char **path_B)
Parse arguments used by the transfer commands.
int dts_xferParsePaths (char *host, char **path_A, char **path_B, int *srcLocal, int *dstLocal, char **src_host, char **dest_host, char **msg_host, char **path)
Parse the paths used by the transfer commands.
Variables
DTS * dts
int dts_monitor
Detailed Description
Client-callable DTS commands to transfer files TO a remote host machine..
DTSHOTTO.C -- Client-callable DTS commands to transfer files TO a remote host machine..
Author: Mike Fitzpatrick, NOAO
Date: 6/15/09
Function Documentation
int dts_hostFrom (char * host, int port, int method, int rate, int loPort, int hiPort, int threads, int mode, int argc, char * argv[], xferStat * xfs)
Pull a file from a remote host.
DTS_HOSTFROM -- Pull a file from A to B.
Parameters:
host host machine name (or IP string)
port local DTS command port
method transport method
rate transport rate (Mbps)
loPort low DTS transfer port
hiPort high DTS transfer port
threads number of transfer threads
mode transfer mode
argc argument counter
argv argument vector
xfs transfer stats
Returns: 1 (one) if DTS succeeds.
References dts_cmdInit(), dts_getLocalIP(), dts_hostAccess(), dts_hostFMode(), dts_hostFSize(), dts_hostIsDir(), dts_hostMkdir(), dts_localMkdir(), dts_pathDir(), dts_pathFname(), dts_queueFromPath(), dts_resolveHost(), dts_xferDirFrom(), dts_xferFile(), dts_xferParseArgs(), and dtsLog().
int dts_hostTo (char * host, int port, int method, int rate, int loPort, int hiPort, int threads, int mode, int argc, char * argv[], xferStat * xfs)
Push a file to a remote host.
DTS_HOSTTO -- Move a file from A 'to' B (i.e. a `push` or `give`).
Parameters:
host host machine name (or IP string)
port local DTS command port
method transport method
rate transfer rate (Mbps)
loPort low DTS transfer port
hiPort high DTS transfer port
threads number of transfer threads
mode transfer mode
argc argument counter
argv argument vector
xfs transfer stats
Returns: 1 (one) if DTS succeeds.
References dts_cmdInit(), dts_du(), dts_getLocalIP(), dts_hostMkdir(), dts_isDir(), dts_pathDir(), dts_pathFname(), dts_queueFromPath(), dts_xferDirTo(), dts_xferFile(), dts_xferParseArgs(), dts_xferParsePaths(), and dtsLog().
Referenced by dts_queueProcess().
int dts_xferDirFrom (char * srcHost, char * dstHost, int dstLocal, char * func, int method, int rate, char * path, char * root, char * prefix, xferStat * xs)
Recursively transfer a directory between hosts.
DTS_XFERDIRFROM -- Recursively transfer a directory between hosts.
Parameters:
srcHost source host
dstHost destination host
dstLocal is dest the local machine?
func RPC method to call
method transport method
rate transfer rate
path path to file
root destination root
prefix destination path prefix
xfs transfer stats
Returns: 1 (one) if DTS succeeds.
References dts_hostDir(), dts_hostFMode(), dts_hostFSize(), dts_pathDir(), dts_pathFname(), dts_xferFile(), and dtsErrLog().
Referenced by dts_hostFrom().
int dts_xferDirTo (char * host, char * func, int method, int rate, char * path, char * root, char * prefix, xferStat * xs)
Recursively transfer a directory between hosts.
DTS_XFERDIRTO -- Recursively transfer a directory between hosts.
Parameters:
host host to call
func RPC method to call
method transport method
rate transfer rate
path path to file
root destination root
prefix source prefix dir
xfs transfer stats
Returns: 1 (one) if DTS succeeds.
References dts_hostChmod(), dts_hostMkdir(), dts_isDir(), dts_nameMode(), dts_nameSize(), dts_pathDir(), dts_pathFname(), dts_xferFile(), and dtsErrLog().
Referenced by dts_hostTo().
int dts_xferFile (char * host, char * func, int method, int rate, char * path, int fsize, mode_t fmode, xferStat * xs)
Transfer a single file between hosts.
DTS_XFERFILE -- Transfer a single file between hosts.
Parameters:
host client host
func RPC method to call
method transport method
rate transfer rate (Mbps)
path path to file
fsize file size
fmode file protection mode
xfs transfer stats
Returns: 1 (one) if DTS succeeds.
References dts_cfgQMethodStr(), dts_closeClient(), dts_getClient(), dts_hostChmod(), dts_hostIsDir(), dts_hostMkdir(), dts_hostTouch(), dts_isDir(), dts_localMkdir(), dts_localTouch(), dts_nameMode(), dtsErrLog(), transferMB(), and transferMb().
Referenced by dts_hostFrom(), dts_hostTo(), dts_xferDirFrom(), and dts_xferDirTo().
int dts_xferParseArgs (int argc, char * argv[], int * nthreads, int * port, int * verbose, char ** path_A, char ** path_B)
Parse arguments used by the transfer commands.
DTS_XFERPARSEARGS -- Parse the arguments used in the push/pull and give/take commands.
Parameters:
argc arg count
argv arg vector
nthreads number of processing threads
verbose verbose flag
port base transfer port
path_A src path specification
path_B dest path specification
Returns: status code
Referenced by dts_hostFrom(), and dts_hostTo().
int dts_xferParsePaths (char * host, char ** path_A, char ** path_B, int * srcLocal, int * dstLocal, char ** src_host, char ** dest_host, char ** msg_host, char ** path)
Parse the paths used by the transfer commands.
DTS_XFERPARSEPATHS -- Parse the paths used in the transfer.
Parameters:
host host name
path_A src path specification
path_B dest path specification
srcLocal is src local machine?
dstLocal is dest local machine?
srcHost source host name
dstHost dest host name
msgHost message host name
path path name
Returns: status code
References dts_getLocalIP(), and dts_resolveHost().
Referenced by dts_hostTo().