xrHandles.c File Reference
Utility methods to convert client pointers to user handles.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
#include <xmlrpc-c/base.h>
#include <xmlrpc-c/client.h>
#include <xmlrpc-c/server.h>
#include <xmlrpc-c/server_abyss.h>
#include `xrpcP.h`
Defines
#define MAX_HANDLES 8192
#define HANDLE_DEBUG 0
#define START_H 3
Functions
void xr_initHandles (void)
Initialize the handles structure.
void xr_cleanupHandles (void)
Cleanup the handles structure.
handle_t xr_setHandle (int handle, void *ptr)
Set the handle manually.
handle_t xr_newHandle (void *ptr)
Get an unused object handle.
void xr_freeHandle (handle_t handle)
Free the handle for later re-use.
handle_t xr_P2H (void *ptr)
Convert a pointer to a handle.
void * xr_H2P (handle_t handle)
Variables
int numXrHandles = START_H
handle_t xrHandles [MAX_HANDLES]
Detailed Description
Utility methods to convert client pointers to user handles.
XRHANDLE.C -- Utility methods to convert client pointers to user handles.
Author: Mike Fitzpatrick
Date: April 2014
Function Documentation
void xr_cleanupHandles (void)
Cleanup the handles structure.
XR_CLEANUPHANDLES -- Cleanup the handles structure.
Returns: nothing
xr_freeHandle (handle_t handle)
Free the handle for later re-use.
XR_FREEHANDLE -- Free the handle for later re-use.
Parameters:
handle object handle
Returns: nothing
void xr_initHandles (void)
Initialize the handles structure.
XR_INITHANDLES -- Initialize the handles structure.
Returns: nothing
Referenced by xr_newHandle(), and xr_setHandle().
handle_t xr_newHandle (void * ptr)
Get an unused object handle.
XR_NEWHANDLE -- Get an unused object handle.
Parameters:
ptr pointer to object to be stored
Returns: new object handle
References xr_initHandles().
handle_t xr_P2H (void * ptr)
Convert a pointer to a handle.
XR_P2H -- Convert a pointer to a handle
Parameters:
ptr pointer to object
Returns: handle to object, < 0 on error
handle_t xr_setHandle (int handle, void * ptr)
Set the handle manually.
XR_SETHANDLE -- Set the handle manually.
Parameters:
handle handle to be used
ptr pointer to object to be stored
Returns: new object handle
References xr_initHandles().