#!/bin/csh -f


foreach d (*.man)
  echo -n "$d .... "
    set doc = $d:r
    groff -man -T ps ${doc}.man > ${doc}.ps
    ps2pdf ${doc}.ps ; /bin/rm -f ${doc}.ps
    man2html ${doc}.man > ${doc}.html
  echo "done"
end
