"\n"
"################################################\n"
"#  DES/DECam Recovery Queues\n"
"################################################\n"
"\n"
"queue\n"
"       name        des_r\n"
"       host        dsas3.ctio.noao.edu\n"
"       dir         default\n"
"       method      give\n"
"       port        2150\n"
"       nthreads    4\n"
"\n"
"queue\n"
"       name        decam_r\n"
"       host        dsas3.ctio.noao.edu\n"
"       dir         default\n"
"       method      give\n"
"       port        2130\n"
"       nthreads    4\n"
"\n"
"\n"
